# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test Body")

model.instance <- Body$new()

test_that("object_identifier", {
  # tests for the property `object_identifier` (character)
  # The full identifier of data object that needs to be evaluated

  # uncomment below to test the property 
  #expect_equal(model.instance$`object_identifier`, "EXPECTED_RESULT")
})

test_that("test_debug", {
  # tests for the property `test_debug` (character)
  # Indicate if the detailed evaluation procedure of the metrics should to be included in the response

  # uncomment below to test the property 
  #expect_equal(model.instance$`test_debug`, "EXPECTED_RESULT")
})

test_that("metadata_service_endpoint", {
  # tests for the property `metadata_service_endpoint` (character)
  # The URL of the catalogue endpoint (e.g. OAI-PMH data-provider)

  # uncomment below to test the property 
  #expect_equal(model.instance$`metadata_service_endpoint`, "EXPECTED_RESULT")
})

test_that("metadata_service_type", {
  # tests for the property `metadata_service_type` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`metadata_service_type`, "EXPECTED_RESULT")
})

test_that("use_datacite", {
  # tests for the property `use_datacite` (character)
  # Indicates if DataCite content negotiation (using the DOI) shall be used to collect metadata

  # uncomment below to test the property 
  #expect_equal(model.instance$`use_datacite`, "EXPECTED_RESULT")
})

test_that("oaipmh_endpoint", {
  # tests for the property `oaipmh_endpoint` (character)
  # (Deprecated) The URL of the OAI-PMH data-provider

  # uncomment below to test the property 
  #expect_equal(model.instance$`oaipmh_endpoint`, "EXPECTED_RESULT")
})

