# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test Metric")

model.instance <- Metric$new()

test_that("metric_identifier", {
  # tests for the property `metric_identifier` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`metric_identifier`, "EXPECTED_RESULT")
})

test_that("metric_name", {
  # tests for the property `metric_name` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`metric_name`, "EXPECTED_RESULT")
})

test_that("description", {
  # tests for the property `description` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`description`, "EXPECTED_RESULT")
})

test_that("fair_principle", {
  # tests for the property `fair_principle` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`fair_principle`, "EXPECTED_RESULT")
})

test_that("evaluation_mechanism", {
  # tests for the property `evaluation_mechanism` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`evaluation_mechanism`, "EXPECTED_RESULT")
})

test_that("date_created", {
  # tests for the property `date_created` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`date_created`, "EXPECTED_RESULT")
})

test_that("date_updated", {
  # tests for the property `date_updated` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`date_updated`, "EXPECTED_RESULT")
})

test_that("created_by", {
  # tests for the property `created_by` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`created_by`, "EXPECTED_RESULT")
})

test_that("version", {
  # tests for the property `version` (numeric)

  # uncomment below to test the property 
  #expect_equal(model.instance$`version`, "EXPECTED_RESULT")
})

test_that("total_score", {
  # tests for the property `total_score` (integer)

  # uncomment below to test the property 
  #expect_equal(model.instance$`total_score`, "EXPECTED_RESULT")
})

