# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test UniquenessOutput")

model.instance <- UniquenessOutput$new()

test_that("guid", {
  # tests for the property `guid` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`guid`, "EXPECTED_RESULT")
})

test_that("guid_scheme", {
  # tests for the property `guid_scheme` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`guid_scheme`, "EXPECTED_RESULT")
})

