# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test FormalMetadata")

model.instance <- FormalMetadata$new()

test_that("id", {
  # tests for the property `id` (integer)

  # uncomment below to test the property 
  #expect_equal(model.instance$`id`, "EXPECTED_RESULT")
})

test_that("metric_identifier", {
  # tests for the property `metric_identifier` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`metric_identifier`, "EXPECTED_RESULT")
})

test_that("metric_name", {
  # tests for the property `metric_name` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`metric_name`, "EXPECTED_RESULT")
})

test_that("metric_tests", {
  # tests for the property `metric_tests` (map(FAIRResultEvaluationCriterium))

  # uncomment below to test the property 
  #expect_equal(model.instance$`metric_tests`, "EXPECTED_RESULT")
})

test_that("test_status", {
  # tests for the property `test_status` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`test_status`, "EXPECTED_RESULT")
})

test_that("score", {
  # tests for the property `score` (FAIRResultCommonScore)

  # uncomment below to test the property 
  #expect_equal(model.instance$`score`, "EXPECTED_RESULT")
})

test_that("maturity", {
  # tests for the property `maturity` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`maturity`, "EXPECTED_RESULT")
})

test_that("output", {
  # tests for the property `output` (array[FormalMetadataOutputInner])

  # uncomment below to test the property 
  #expect_equal(model.instance$`output`, "EXPECTED_RESULT")
})

test_that("test_debug", {
  # tests for the property `test_debug` (array[character])

  # uncomment below to test the property 
  #expect_equal(model.instance$`test_debug`, "EXPECTED_RESULT")
})

