# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test StandardisedProtocolMetadataOutput")

model.instance <- StandardisedProtocolMetadataOutput$new()

test_that("standard_metadata_protocol", {
  # tests for the property `standard_metadata_protocol` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`standard_metadata_protocol`, "EXPECTED_RESULT")
})

