# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test FormalMetadataOutputInner")

model.instance <- FormalMetadataOutputInner$new()

test_that("serialization_format", {
  # tests for the property `serialization_format` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`serialization_format`, "EXPECTED_RESULT")
})

test_that("source", {
  # tests for the property `source` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`source`, "EXPECTED_RESULT")
})

test_that("is_metadata_found", {
  # tests for the property `is_metadata_found` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`is_metadata_found`, "EXPECTED_RESULT")
})

