# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test LicenseOutputInner")

model.instance <- LicenseOutputInner$new()

test_that("license", {
  # tests for the property `license` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`license`, "EXPECTED_RESULT")
})

test_that("OSI_approved", {
  # tests for the property `OSI_approved` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`OSI_approved`, "EXPECTED_RESULT")
})

test_that("details_url", {
  # tests for the property `details_url` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`details_url`, "EXPECTED_RESULT")
})

