# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test DataProvenanceOutput")

model.instance <- DataProvenanceOutput$new()

test_that("provenance_metadata_included", {
  # tests for the property `provenance_metadata_included` (DataProvenanceOutputInner)

  # uncomment below to test the property 
  #expect_equal(model.instance$`provenance_metadata_included`, "EXPECTED_RESULT")
})

test_that("structured_provenance_available", {
  # tests for the property `structured_provenance_available` (DataProvenanceOutputInner)

  # uncomment below to test the property 
  #expect_equal(model.instance$`structured_provenance_available`, "EXPECTED_RESULT")
})

