# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test MetadataPreservedOutput")

model.instance <- MetadataPreservedOutput$new()

test_that("metadata_preservation_method", {
  # tests for the property `metadata_preservation_method` (array[character])

  # uncomment below to test the property 
  #expect_equal(model.instance$`metadata_preservation_method`, "EXPECTED_RESULT")
})

