# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test FAIRMetricApi")

api.instance <- FAIRMetricApi$new()

test_that("GetMetrics", {
  # tests for GetMetrics
  # base path: http://localhost:1071/fuji/api/v1
  # Return all metrics and their definitions
  # @return [Metrics]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

