# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test SearchableOutput")

model.instance <- SearchableOutput$new()

test_that("search_mechanisms", {
  # tests for the property `search_mechanisms` (array[OutputSearchMechanisms])

  # uncomment below to test the property 
  #expect_equal(model.instance$`search_mechanisms`, "EXPECTED_RESULT")
})

