# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test DataAccessOutput")

model.instance <- DataAccessOutput$new()

test_that("access_level", {
  # tests for the property `access_level` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`access_level`, "EXPECTED_RESULT")
})

test_that("access_details", {
  # tests for the property `access_details` (object)

  # uncomment below to test the property 
  #expect_equal(model.instance$`access_details`, "EXPECTED_RESULT")
})

