# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test DataProvenanceOutputInner")

model.instance <- DataProvenanceOutputInner$new()

test_that("is_available", {
  # tests for the property `is_available` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`is_available`, "EXPECTED_RESULT")
})

test_that("provenance_metadata", {
  # tests for the property `provenance_metadata` (array[map(character)])

  # uncomment below to test the property 
  #expect_equal(model.instance$`provenance_metadata`, "EXPECTED_RESULT")
})

