# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test CommunityEndorsedStandardOutputInner")

model.instance <- CommunityEndorsedStandardOutputInner$new()

test_that("metadata_standard", {
  # tests for the property `metadata_standard` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`metadata_standard`, "EXPECTED_RESULT")
})

test_that("urls", {
  # tests for the property `urls` (array[character])

  # uncomment below to test the property 
  #expect_equal(model.instance$`urls`, "EXPECTED_RESULT")
})

test_that("subject_areas", {
  # tests for the property `subject_areas` (array[character])

  # uncomment below to test the property 
  #expect_equal(model.instance$`subject_areas`, "EXPECTED_RESULT")
})

