# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test DataContentMetadataOutputInner")

model.instance <- DataContentMetadataOutputInner$new()

test_that("descriptor", {
  # tests for the property `descriptor` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`descriptor`, "EXPECTED_RESULT")
})

test_that("descriptor_value", {
  # tests for the property `descriptor_value` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`descriptor_value`, "EXPECTED_RESULT")
})

test_that("matches_content", {
  # tests for the property `matches_content` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`matches_content`, "EXPECTED_RESULT")
})

