# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test FAIRObjectApi")

api.instance <- FAIRObjectApi$new()

test_that("AssessById", {
  # tests for AssessById
  # base path: http://localhost:1071/fuji/api/v1
  # Evaluate FAIRness of a data object based on its identifier
  # @param body Body  (optional)
  # @return [FAIRResults]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

