# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test OutputSearchMechanisms")

model.instance <- OutputSearchMechanisms$new()

test_that("mechanism", {
  # tests for the property `mechanism` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`mechanism`, "EXPECTED_RESULT")
})

test_that("mechanism_info", {
  # tests for the property `mechanism_info` (array[character])

  # uncomment below to test the property 
  #expect_equal(model.instance$`mechanism_info`, "EXPECTED_RESULT")
})

