# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test CoreMetadataOutput")

model.instance <- CoreMetadataOutput$new()

test_that("core_metadata_status", {
  # tests for the property `core_metadata_status` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`core_metadata_status`, "EXPECTED_RESULT")
})

test_that("core_metadata_found", {
  # tests for the property `core_metadata_found` (OutputCoreMetadataFound)

  # uncomment below to test the property 
  #expect_equal(model.instance$`core_metadata_found`, "EXPECTED_RESULT")
})

test_that("core_metadata_source", {
  # tests for the property `core_metadata_source` (array[character])

  # uncomment below to test the property 
  #expect_equal(model.instance$`core_metadata_source`, "EXPECTED_RESULT")
})

