# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test RelatedResourceOutputInner")

model.instance <- RelatedResourceOutputInner$new()

test_that("related_resource", {
  # tests for the property `related_resource` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`related_resource`, "EXPECTED_RESULT")
})

test_that("relation_type", {
  # tests for the property `relation_type` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`relation_type`, "EXPECTED_RESULT")
})

