# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test PersistenceOutput")

model.instance <- PersistenceOutput$new()

test_that("pid", {
  # tests for the property `pid` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`pid`, "EXPECTED_RESULT")
})

test_that("pid_scheme", {
  # tests for the property `pid_scheme` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`pid_scheme`, "EXPECTED_RESULT")
})

test_that("resolvable_status", {
  # tests for the property `resolvable_status` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`resolvable_status`, "EXPECTED_RESULT")
})

test_that("resolved_url", {
  # tests for the property `resolved_url` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`resolved_url`, "EXPECTED_RESULT")
})

