# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test IdentifierIncludedOutputInner")

model.instance <- IdentifierIncludedOutputInner$new()

test_that("content_identifier_included", {
  # tests for the property `content_identifier_included` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`content_identifier_included`, "EXPECTED_RESULT")
})

test_that("content_identifier_active", {
  # tests for the property `content_identifier_active` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`content_identifier_active`, "EXPECTED_RESULT")
})

