# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test IdentifierIncludedOutput")

model.instance <- IdentifierIncludedOutput$new()

test_that("object_identifier_included", {
  # tests for the property `object_identifier_included` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`object_identifier_included`, "EXPECTED_RESULT")
})

test_that("content", {
  # tests for the property `content` (array[IdentifierIncludedOutputInner])

  # uncomment below to test the property 
  #expect_equal(model.instance$`content`, "EXPECTED_RESULT")
})

