# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test DataContentMetadataOutput")

model.instance <- DataContentMetadataOutput$new()

test_that("object_type", {
  # tests for the property `object_type` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`object_type`, "EXPECTED_RESULT")
})

test_that("data_content_descriptor", {
  # tests for the property `data_content_descriptor` (array[DataContentMetadataOutputInner])

  # uncomment below to test the property 
  #expect_equal(model.instance$`data_content_descriptor`, "EXPECTED_RESULT")
})

