# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test MetadataPreservedAllOf")

model.instance <- MetadataPreservedAllOf$new()

test_that("output", {
  # tests for the property `output` (MetadataPreservedOutput)

  # uncomment below to test the property 
  #expect_equal(model.instance$`output`, "EXPECTED_RESULT")
})

test_that("test_debug", {
  # tests for the property `test_debug` (array[character])

  # uncomment below to test the property 
  #expect_equal(model.instance$`test_debug`, "EXPECTED_RESULT")
})

