# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test DataFileFormatOutputInner")

model.instance <- DataFileFormatOutputInner$new()

test_that("file_uri", {
  # tests for the property `file_uri` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`file_uri`, "EXPECTED_RESULT")
})

test_that("mime_type", {
  # tests for the property `mime_type` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`mime_type`, "EXPECTED_RESULT")
})

test_that("is_preferred_format", {
  # tests for the property `is_preferred_format` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`is_preferred_format`, "EXPECTED_RESULT")
})

test_that("preference_reason", {
  # tests for the property `preference_reason` (array[character])

  # uncomment below to test the property 
  #expect_equal(model.instance$`preference_reason`, "EXPECTED_RESULT")
})

test_that("subject_areas", {
  # tests for the property `subject_areas` (array[character])

  # uncomment below to test the property 
  #expect_equal(model.instance$`subject_areas`, "EXPECTED_RESULT")
})

