# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test OutputCoreMetadataFound")

model.instance <- OutputCoreMetadataFound$new()

test_that("creator", {
  # tests for the property `creator` (array[character])

  # uncomment below to test the property 
  #expect_equal(model.instance$`creator`, "EXPECTED_RESULT")
})

test_that("title", {
  # tests for the property `title` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`title`, "EXPECTED_RESULT")
})

test_that("publisher", {
  # tests for the property `publisher` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`publisher`, "EXPECTED_RESULT")
})

test_that("publication_date", {
  # tests for the property `publication_date` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`publication_date`, "EXPECTED_RESULT")
})

test_that("summary", {
  # tests for the property `summary` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`summary`, "EXPECTED_RESULT")
})

test_that("keywords", {
  # tests for the property `keywords` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`keywords`, "EXPECTED_RESULT")
})

test_that("object_identifier", {
  # tests for the property `object_identifier` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`object_identifier`, "EXPECTED_RESULT")
})

