# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test Metrics")

model.instance <- Metrics$new()

test_that("total", {
  # tests for the property `total` (integer)

  # uncomment below to test the property 
  #expect_equal(model.instance$`total`, "EXPECTED_RESULT")
})

test_that("metrics", {
  # tests for the property `metrics` (array[Metric])

  # uncomment below to test the property 
  #expect_equal(model.instance$`metrics`, "EXPECTED_RESULT")
})

