# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test StandardisedProtocolDataOutput")

model.instance <- StandardisedProtocolDataOutput$new()

test_that("standard_data_protocol", {
  # tests for the property `standard_data_protocol` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`standard_data_protocol`, "EXPECTED_RESULT")
})

