# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test SemanticVocabularyOutputInner")

model.instance <- SemanticVocabularyOutputInner$new()

test_that("namespace", {
  # tests for the property `namespace` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`namespace`, "EXPECTED_RESULT")
})

test_that("is_namespace_active", {
  # tests for the property `is_namespace_active` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`is_namespace_active`, "EXPECTED_RESULT")
})

