# F-UJI
#
# A Service for Evaluating Research Data Objects Based on <a href ='https://doi.org/10.5281/zenodo.3775793'>FAIRsFAIR Metrics</a>. <p> This work was supported by the <a href='https://www.fairsfair.eu/'>FAIRsFAIR</a> project (H2020-INFRAEOSC-2018-2020 Grant Agreement 831558).
#
# The version of the OpenAPI document: 1.1.0
# Contact: anusuriya.devaraju@googlemail.com
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title Body
#'
#' @description Body Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field object_identifier  character 
#'
#' @field test_debug  character [optional]
#'
#' @field metadata_service_endpoint  character [optional]
#'
#' @field metadata_service_type  character [optional]
#'
#' @field use_datacite  character [optional]
#'
#' @field oaipmh_endpoint  character [optional]
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
Body <- R6::R6Class(
  'Body',
  public = list(
    `object_identifier` = NULL,
    `test_debug` = NULL,
    `metadata_service_endpoint` = NULL,
    `metadata_service_type` = NULL,
    `use_datacite` = NULL,
    `oaipmh_endpoint` = NULL,
    initialize = function(
        `object_identifier`, `test_debug`=FALSE, `metadata_service_endpoint`=NULL, `metadata_service_type`=NULL, `use_datacite`=NULL, `oaipmh_endpoint`=NULL, ...
    ) {
      local.optional.var <- list(...)
      if (!missing(`object_identifier`)) {
        stopifnot(is.character(`object_identifier`), length(`object_identifier`) == 1)
        self$`object_identifier` <- `object_identifier`
      }
      if (!is.null(`test_debug`)) {
        stopifnot(is.logical(`test_debug`), length(`test_debug`) == 1)
        self$`test_debug` <- `test_debug`
      }
      if (!is.null(`metadata_service_endpoint`)) {
        stopifnot(is.character(`metadata_service_endpoint`), length(`metadata_service_endpoint`) == 1)
        self$`metadata_service_endpoint` <- `metadata_service_endpoint`
      }
      if (!is.null(`metadata_service_type`)) {
        stopifnot(is.character(`metadata_service_type`), length(`metadata_service_type`) == 1)
        self$`metadata_service_type` <- `metadata_service_type`
      }
      if (!is.null(`use_datacite`)) {
        stopifnot(is.logical(`use_datacite`), length(`use_datacite`) == 1)
        self$`use_datacite` <- `use_datacite`
      }
      if (!is.null(`oaipmh_endpoint`)) {
        stopifnot(is.character(`oaipmh_endpoint`), length(`oaipmh_endpoint`) == 1)
        self$`oaipmh_endpoint` <- `oaipmh_endpoint`
      }
    },
    toJSON = function() {
      BodyObject <- list()
      if (!is.null(self$`object_identifier`)) {
        BodyObject[['object_identifier']] <-
          self$`object_identifier`
      }
      if (!is.null(self$`test_debug`)) {
        BodyObject[['test_debug']] <-
          self$`test_debug`
      }
      if (!is.null(self$`metadata_service_endpoint`)) {
        BodyObject[['metadata_service_endpoint']] <-
          self$`metadata_service_endpoint`
      }
      if (!is.null(self$`metadata_service_type`)) {
        BodyObject[['metadata_service_type']] <-
          self$`metadata_service_type`
      }
      if (!is.null(self$`use_datacite`)) {
        BodyObject[['use_datacite']] <-
          self$`use_datacite`
      }
      if (!is.null(self$`oaipmh_endpoint`)) {
        BodyObject[['oaipmh_endpoint']] <-
          self$`oaipmh_endpoint`
      }

      BodyObject
    },
    fromJSON = function(BodyJson) {
      BodyObject <- jsonlite::fromJSON(BodyJson)
      if (!is.null(BodyObject$`object_identifier`)) {
        self$`object_identifier` <- BodyObject$`object_identifier`
      }
      if (!is.null(BodyObject$`test_debug`)) {
        self$`test_debug` <- BodyObject$`test_debug`
      }
      if (!is.null(BodyObject$`metadata_service_endpoint`)) {
        self$`metadata_service_endpoint` <- BodyObject$`metadata_service_endpoint`
      }
      if (!is.null(BodyObject$`metadata_service_type`)) {
        self$`metadata_service_type` <- BodyObject$`metadata_service_type`
      }
      if (!is.null(BodyObject$`use_datacite`)) {
        self$`use_datacite` <- BodyObject$`use_datacite`
      }
      if (!is.null(BodyObject$`oaipmh_endpoint`)) {
        self$`oaipmh_endpoint` <- BodyObject$`oaipmh_endpoint`
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`object_identifier`)) {
        sprintf(
        '"object_identifier":
          "%s"
                ',
        self$`object_identifier`
        )},
        if (!is.null(self$`test_debug`)) {
        sprintf(
        '"test_debug":
          %s
                ',
        tolower(self$`test_debug`)
        )},
        if (!is.null(self$`metadata_service_endpoint`)) {
        sprintf(
        '"metadata_service_endpoint":
          "%s"
                ',
        self$`metadata_service_endpoint`
        )},
        if (!is.null(self$`metadata_service_type`)) {
        sprintf(
        '"metadata_service_type":
          "%s"
                ',
        self$`metadata_service_type`
        )},
        if (!is.null(self$`use_datacite`)) {
        sprintf(
        '"use_datacite":
          %s
                ',
        tolower(self$`use_datacite`)
        )},
        if (!is.null(self$`oaipmh_endpoint`)) {
        sprintf(
        '"oaipmh_endpoint":
          "%s"
                ',
        self$`oaipmh_endpoint`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(BodyJson) {
      BodyObject <- jsonlite::fromJSON(BodyJson)
      self$`object_identifier` <- BodyObject$`object_identifier`
      self$`test_debug` <- BodyObject$`test_debug`
      self$`metadata_service_endpoint` <- BodyObject$`metadata_service_endpoint`
      self$`metadata_service_type` <- BodyObject$`metadata_service_type`
      self$`use_datacite` <- BodyObject$`use_datacite`
      self$`oaipmh_endpoint` <- BodyObject$`oaipmh_endpoint`
      self
    }
  )
)
