# F-UJI
#
# A Service for Evaluating Research Data Objects Based on <a href ='https://doi.org/10.5281/zenodo.3775793'>FAIRsFAIR Metrics</a>. <p> This work was supported by the <a href='https://www.fairsfair.eu/'>FAIRsFAIR</a> project (H2020-INFRAEOSC-2018-2020 Grant Agreement 831558).
#
# The version of the OpenAPI document: 1.1.0
# Contact: anusuriya.devaraju@googlemail.com
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title CommunityEndorsedStandardOutputInner
#'
#' @description CommunityEndorsedStandardOutputInner Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field metadata_standard  character [optional]
#'
#' @field urls  list( character ) [optional]
#'
#' @field subject_areas  list( character ) [optional]
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
CommunityEndorsedStandardOutputInner <- R6::R6Class(
  'CommunityEndorsedStandardOutputInner',
  public = list(
    `metadata_standard` = NULL,
    `urls` = NULL,
    `subject_areas` = NULL,
    initialize = function(
        `metadata_standard`=NULL, `urls`=NULL, `subject_areas`=NULL, ...
    ) {
      local.optional.var <- list(...)
      if (!is.null(`metadata_standard`)) {
        stopifnot(is.character(`metadata_standard`), length(`metadata_standard`) == 1)
        self$`metadata_standard` <- `metadata_standard`
      }
      if (!is.null(`urls`)) {
        stopifnot(is.vector(`urls`), length(`urls`) != 0)
        sapply(`urls`, function(x) stopifnot(is.character(x)))
        self$`urls` <- `urls`
      }
      if (!is.null(`subject_areas`)) {
        stopifnot(is.vector(`subject_areas`), length(`subject_areas`) != 0)
        sapply(`subject_areas`, function(x) stopifnot(is.character(x)))
        self$`subject_areas` <- `subject_areas`
      }
    },
    toJSON = function() {
      CommunityEndorsedStandardOutputInnerObject <- list()
      if (!is.null(self$`metadata_standard`)) {
        CommunityEndorsedStandardOutputInnerObject[['metadata_standard']] <-
          self$`metadata_standard`
      }
      if (!is.null(self$`urls`)) {
        CommunityEndorsedStandardOutputInnerObject[['urls']] <-
          self$`urls`
      }
      if (!is.null(self$`subject_areas`)) {
        CommunityEndorsedStandardOutputInnerObject[['subject_areas']] <-
          self$`subject_areas`
      }

      CommunityEndorsedStandardOutputInnerObject
    },
    fromJSON = function(CommunityEndorsedStandardOutputInnerJson) {
      CommunityEndorsedStandardOutputInnerObject <- jsonlite::fromJSON(CommunityEndorsedStandardOutputInnerJson)
      if (!is.null(CommunityEndorsedStandardOutputInnerObject$`metadata_standard`)) {
        self$`metadata_standard` <- CommunityEndorsedStandardOutputInnerObject$`metadata_standard`
      }
      if (!is.null(CommunityEndorsedStandardOutputInnerObject$`urls`)) {
        self$`urls` <- ApiClient$new()$deserializeObj(CommunityEndorsedStandardOutputInnerObject$`urls`, "array[character]", loadNamespace("rfuji"))
      }
      if (!is.null(CommunityEndorsedStandardOutputInnerObject$`subject_areas`)) {
        self$`subject_areas` <- ApiClient$new()$deserializeObj(CommunityEndorsedStandardOutputInnerObject$`subject_areas`, "array[character]", loadNamespace("rfuji"))
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`metadata_standard`)) {
        sprintf(
        '"metadata_standard":
          "%s"
                ',
        self$`metadata_standard`
        )},
        if (!is.null(self$`urls`)) {
        sprintf(
        '"urls":
           [%s]
        ',
        paste(unlist(lapply(self$`urls`, function(x) paste0('"', x, '"'))), collapse=",")
        )},
        if (!is.null(self$`subject_areas`)) {
        sprintf(
        '"subject_areas":
           [%s]
        ',
        paste(unlist(lapply(self$`subject_areas`, function(x) paste0('"', x, '"'))), collapse=",")
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(CommunityEndorsedStandardOutputInnerJson) {
      CommunityEndorsedStandardOutputInnerObject <- jsonlite::fromJSON(CommunityEndorsedStandardOutputInnerJson)
      self$`metadata_standard` <- CommunityEndorsedStandardOutputInnerObject$`metadata_standard`
      self$`urls` <- ApiClient$new()$deserializeObj(CommunityEndorsedStandardOutputInnerObject$`urls`, "array[character]", loadNamespace("rfuji"))
      self$`subject_areas` <- ApiClient$new()$deserializeObj(CommunityEndorsedStandardOutputInnerObject$`subject_areas`, "array[character]", loadNamespace("rfuji"))
      self
    }
  )
)
