# F-UJI
#
# A Service for Evaluating Research Data Objects Based on <a href ='https://doi.org/10.5281/zenodo.3775793'>FAIRsFAIR Metrics</a>. <p> This work was supported by the <a href='https://www.fairsfair.eu/'>FAIRsFAIR</a> project (H2020-INFRAEOSC-2018-2020 Grant Agreement 831558).
#
# The version of the OpenAPI document: 1.1.0
# Contact: anusuriya.devaraju@googlemail.com
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title CoreMetadataOutput
#'
#' @description CoreMetadataOutput Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field core_metadata_status  character [optional]
#'
#' @field core_metadata_found  \link{OutputCoreMetadataFound} [optional]
#'
#' @field core_metadata_source  list( character ) [optional]
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
CoreMetadataOutput <- R6::R6Class(
  'CoreMetadataOutput',
  public = list(
    `core_metadata_status` = NULL,
    `core_metadata_found` = NULL,
    `core_metadata_source` = NULL,
    initialize = function(
        `core_metadata_status`=NULL, `core_metadata_found`=NULL, `core_metadata_source`=NULL, ...
    ) {
      local.optional.var <- list(...)
      if (!is.null(`core_metadata_status`)) {
        stopifnot(is.character(`core_metadata_status`), length(`core_metadata_status`) == 1)
        self$`core_metadata_status` <- `core_metadata_status`
      }
      if (!is.null(`core_metadata_found`)) {
        stopifnot(R6::is.R6(`core_metadata_found`))
        self$`core_metadata_found` <- `core_metadata_found`
      }
      if (!is.null(`core_metadata_source`)) {
        stopifnot(is.vector(`core_metadata_source`), length(`core_metadata_source`) != 0)
        sapply(`core_metadata_source`, function(x) stopifnot(is.character(x)))
        self$`core_metadata_source` <- `core_metadata_source`
      }
    },
    toJSON = function() {
      CoreMetadataOutputObject <- list()
      if (!is.null(self$`core_metadata_status`)) {
        CoreMetadataOutputObject[['core_metadata_status']] <-
          self$`core_metadata_status`
      }
      if (!is.null(self$`core_metadata_found`)) {
        CoreMetadataOutputObject[['core_metadata_found']] <-
          self$`core_metadata_found`$toJSON()
      }
      if (!is.null(self$`core_metadata_source`)) {
        CoreMetadataOutputObject[['core_metadata_source']] <-
          self$`core_metadata_source`
      }

      CoreMetadataOutputObject
    },
    fromJSON = function(CoreMetadataOutputJson) {
      CoreMetadataOutputObject <- jsonlite::fromJSON(CoreMetadataOutputJson)
      if (!is.null(CoreMetadataOutputObject$`core_metadata_status`)) {
        self$`core_metadata_status` <- CoreMetadataOutputObject$`core_metadata_status`
      }
      if (!is.null(CoreMetadataOutputObject$`core_metadata_found`)) {
        core_metadata_foundObject <- OutputCoreMetadataFound$new()
        core_metadata_foundObject$fromJSON(jsonlite::toJSON(CoreMetadataOutputObject$core_metadata_found, auto_unbox = TRUE, digits = NA))
        self$`core_metadata_found` <- core_metadata_foundObject
      }
      if (!is.null(CoreMetadataOutputObject$`core_metadata_source`)) {
        self$`core_metadata_source` <- ApiClient$new()$deserializeObj(CoreMetadataOutputObject$`core_metadata_source`, "array[character]", loadNamespace("rfuji"))
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`core_metadata_status`)) {
        sprintf(
        '"core_metadata_status":
          "%s"
                ',
        self$`core_metadata_status`
        )},
        if (!is.null(self$`core_metadata_found`)) {
        sprintf(
        '"core_metadata_found":
        %s
        ',
        jsonlite::toJSON(self$`core_metadata_found`$toJSON(), auto_unbox=TRUE, digits = NA)
        )},
        if (!is.null(self$`core_metadata_source`)) {
        sprintf(
        '"core_metadata_source":
           [%s]
        ',
        paste(unlist(lapply(self$`core_metadata_source`, function(x) paste0('"', x, '"'))), collapse=",")
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(CoreMetadataOutputJson) {
      CoreMetadataOutputObject <- jsonlite::fromJSON(CoreMetadataOutputJson)
      self$`core_metadata_status` <- CoreMetadataOutputObject$`core_metadata_status`
      self$`core_metadata_found` <- OutputCoreMetadataFound$new()$fromJSON(jsonlite::toJSON(CoreMetadataOutputObject$core_metadata_found, auto_unbox = TRUE, digits = NA))
      self$`core_metadata_source` <- ApiClient$new()$deserializeObj(CoreMetadataOutputObject$`core_metadata_source`, "array[character]", loadNamespace("rfuji"))
      self
    }
  )
)
