# F-UJI
#
# A Service for Evaluating Research Data Objects Based on <a href ='https://doi.org/10.5281/zenodo.3775793'>FAIRsFAIR Metrics</a>. <p> This work was supported by the <a href='https://www.fairsfair.eu/'>FAIRsFAIR</a> project (H2020-INFRAEOSC-2018-2020 Grant Agreement 831558).
#
# The version of the OpenAPI document: 1.1.0
# Contact: anusuriya.devaraju@googlemail.com
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title DataFileFormatOutputInner
#'
#' @description DataFileFormatOutputInner Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field file_uri  character [optional]
#'
#' @field mime_type  character [optional]
#'
#' @field is_preferred_format  character [optional]
#'
#' @field preference_reason  list( character ) [optional]
#'
#' @field subject_areas  list( character ) [optional]
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
DataFileFormatOutputInner <- R6::R6Class(
  'DataFileFormatOutputInner',
  public = list(
    `file_uri` = NULL,
    `mime_type` = NULL,
    `is_preferred_format` = NULL,
    `preference_reason` = NULL,
    `subject_areas` = NULL,
    initialize = function(
        `file_uri`=NULL, `mime_type`=NULL, `is_preferred_format`=FALSE, `preference_reason`=NULL, `subject_areas`=NULL, ...
    ) {
      local.optional.var <- list(...)
      if (!is.null(`file_uri`)) {
        stopifnot(is.character(`file_uri`), length(`file_uri`) == 1)
        self$`file_uri` <- `file_uri`
      }
      if (!is.null(`mime_type`)) {
        stopifnot(is.character(`mime_type`), length(`mime_type`) == 1)
        self$`mime_type` <- `mime_type`
      }
      if (!is.null(`is_preferred_format`)) {
        stopifnot(is.logical(`is_preferred_format`), length(`is_preferred_format`) == 1)
        self$`is_preferred_format` <- `is_preferred_format`
      }
      if (!is.null(`preference_reason`)) {
        stopifnot(is.vector(`preference_reason`), length(`preference_reason`) != 0)
        sapply(`preference_reason`, function(x) stopifnot(is.character(x)))
        self$`preference_reason` <- `preference_reason`
      }
      if (!is.null(`subject_areas`)) {
        stopifnot(is.vector(`subject_areas`), length(`subject_areas`) != 0)
        sapply(`subject_areas`, function(x) stopifnot(is.character(x)))
        self$`subject_areas` <- `subject_areas`
      }
    },
    toJSON = function() {
      DataFileFormatOutputInnerObject <- list()
      if (!is.null(self$`file_uri`)) {
        DataFileFormatOutputInnerObject[['file_uri']] <-
          self$`file_uri`
      }
      if (!is.null(self$`mime_type`)) {
        DataFileFormatOutputInnerObject[['mime_type']] <-
          self$`mime_type`
      }
      if (!is.null(self$`is_preferred_format`)) {
        DataFileFormatOutputInnerObject[['is_preferred_format']] <-
          self$`is_preferred_format`
      }
      if (!is.null(self$`preference_reason`)) {
        DataFileFormatOutputInnerObject[['preference_reason']] <-
          self$`preference_reason`
      }
      if (!is.null(self$`subject_areas`)) {
        DataFileFormatOutputInnerObject[['subject_areas']] <-
          self$`subject_areas`
      }

      DataFileFormatOutputInnerObject
    },
    fromJSON = function(DataFileFormatOutputInnerJson) {
      DataFileFormatOutputInnerObject <- jsonlite::fromJSON(DataFileFormatOutputInnerJson)
      if (!is.null(DataFileFormatOutputInnerObject$`file_uri`)) {
        self$`file_uri` <- DataFileFormatOutputInnerObject$`file_uri`
      }
      if (!is.null(DataFileFormatOutputInnerObject$`mime_type`)) {
        self$`mime_type` <- DataFileFormatOutputInnerObject$`mime_type`
      }
      if (!is.null(DataFileFormatOutputInnerObject$`is_preferred_format`)) {
        self$`is_preferred_format` <- DataFileFormatOutputInnerObject$`is_preferred_format`
      }
      if (!is.null(DataFileFormatOutputInnerObject$`preference_reason`)) {
        self$`preference_reason` <- ApiClient$new()$deserializeObj(DataFileFormatOutputInnerObject$`preference_reason`, "array[character]", loadNamespace("rfuji"))
      }
      if (!is.null(DataFileFormatOutputInnerObject$`subject_areas`)) {
        self$`subject_areas` <- ApiClient$new()$deserializeObj(DataFileFormatOutputInnerObject$`subject_areas`, "array[character]", loadNamespace("rfuji"))
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`file_uri`)) {
        sprintf(
        '"file_uri":
          "%s"
                ',
        self$`file_uri`
        )},
        if (!is.null(self$`mime_type`)) {
        sprintf(
        '"mime_type":
          "%s"
                ',
        self$`mime_type`
        )},
        if (!is.null(self$`is_preferred_format`)) {
        sprintf(
        '"is_preferred_format":
          %s
                ',
        tolower(self$`is_preferred_format`)
        )},
        if (!is.null(self$`preference_reason`)) {
        sprintf(
        '"preference_reason":
           [%s]
        ',
        paste(unlist(lapply(self$`preference_reason`, function(x) paste0('"', x, '"'))), collapse=",")
        )},
        if (!is.null(self$`subject_areas`)) {
        sprintf(
        '"subject_areas":
           [%s]
        ',
        paste(unlist(lapply(self$`subject_areas`, function(x) paste0('"', x, '"'))), collapse=",")
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(DataFileFormatOutputInnerJson) {
      DataFileFormatOutputInnerObject <- jsonlite::fromJSON(DataFileFormatOutputInnerJson)
      self$`file_uri` <- DataFileFormatOutputInnerObject$`file_uri`
      self$`mime_type` <- DataFileFormatOutputInnerObject$`mime_type`
      self$`is_preferred_format` <- DataFileFormatOutputInnerObject$`is_preferred_format`
      self$`preference_reason` <- ApiClient$new()$deserializeObj(DataFileFormatOutputInnerObject$`preference_reason`, "array[character]", loadNamespace("rfuji"))
      self$`subject_areas` <- ApiClient$new()$deserializeObj(DataFileFormatOutputInnerObject$`subject_areas`, "array[character]", loadNamespace("rfuji"))
      self
    }
  )
)
