# F-UJI
#
# A Service for Evaluating Research Data Objects Based on <a href ='https://doi.org/10.5281/zenodo.3775793'>FAIRsFAIR Metrics</a>. <p> This work was supported by the <a href='https://www.fairsfair.eu/'>FAIRsFAIR</a> project (H2020-INFRAEOSC-2018-2020 Grant Agreement 831558).
#
# The version of the OpenAPI document: 1.1.0
# Contact: anusuriya.devaraju@googlemail.com
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title DataContentMetadataOutputInner
#'
#' @description DataContentMetadataOutputInner Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field descriptor  character [optional]
#'
#' @field descriptor_value  character [optional]
#'
#' @field matches_content  character [optional]
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
DataContentMetadataOutputInner <- R6::R6Class(
  'DataContentMetadataOutputInner',
  public = list(
    `descriptor` = NULL,
    `descriptor_value` = NULL,
    `matches_content` = NULL,
    initialize = function(
        `descriptor`=NULL, `descriptor_value`=NULL, `matches_content`=FALSE, ...
    ) {
      local.optional.var <- list(...)
      if (!is.null(`descriptor`)) {
        stopifnot(is.character(`descriptor`), length(`descriptor`) == 1)
        self$`descriptor` <- `descriptor`
      }
      if (!is.null(`descriptor_value`)) {
        stopifnot(is.character(`descriptor_value`), length(`descriptor_value`) == 1)
        self$`descriptor_value` <- `descriptor_value`
      }
      if (!is.null(`matches_content`)) {
        stopifnot(is.logical(`matches_content`), length(`matches_content`) == 1)
        self$`matches_content` <- `matches_content`
      }
    },
    toJSON = function() {
      DataContentMetadataOutputInnerObject <- list()
      if (!is.null(self$`descriptor`)) {
        DataContentMetadataOutputInnerObject[['descriptor']] <-
          self$`descriptor`
      }
      if (!is.null(self$`descriptor_value`)) {
        DataContentMetadataOutputInnerObject[['descriptor_value']] <-
          self$`descriptor_value`
      }
      if (!is.null(self$`matches_content`)) {
        DataContentMetadataOutputInnerObject[['matches_content']] <-
          self$`matches_content`
      }

      DataContentMetadataOutputInnerObject
    },
    fromJSON = function(DataContentMetadataOutputInnerJson) {
      DataContentMetadataOutputInnerObject <- jsonlite::fromJSON(DataContentMetadataOutputInnerJson)
      if (!is.null(DataContentMetadataOutputInnerObject$`descriptor`)) {
        self$`descriptor` <- DataContentMetadataOutputInnerObject$`descriptor`
      }
      if (!is.null(DataContentMetadataOutputInnerObject$`descriptor_value`)) {
        self$`descriptor_value` <- DataContentMetadataOutputInnerObject$`descriptor_value`
      }
      if (!is.null(DataContentMetadataOutputInnerObject$`matches_content`)) {
        self$`matches_content` <- DataContentMetadataOutputInnerObject$`matches_content`
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`descriptor`)) {
        sprintf(
        '"descriptor":
          "%s"
                ',
        self$`descriptor`
        )},
        if (!is.null(self$`descriptor_value`)) {
        sprintf(
        '"descriptor_value":
          "%s"
                ',
        self$`descriptor_value`
        )},
        if (!is.null(self$`matches_content`)) {
        sprintf(
        '"matches_content":
          %s
                ',
        tolower(self$`matches_content`)
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(DataContentMetadataOutputInnerJson) {
      DataContentMetadataOutputInnerObject <- jsonlite::fromJSON(DataContentMetadataOutputInnerJson)
      self$`descriptor` <- DataContentMetadataOutputInnerObject$`descriptor`
      self$`descriptor_value` <- DataContentMetadataOutputInnerObject$`descriptor_value`
      self$`matches_content` <- DataContentMetadataOutputInnerObject$`matches_content`
      self
    }
  )
)
