# F-UJI
#
# A Service for Evaluating Research Data Objects Based on <a href ='https://doi.org/10.5281/zenodo.3775793'>FAIRsFAIR Metrics</a>. <p> This work was supported by the <a href='https://www.fairsfair.eu/'>FAIRsFAIR</a> project (H2020-INFRAEOSC-2018-2020 Grant Agreement 831558).
#
# The version of the OpenAPI document: 1.1.0
# Contact: anusuriya.devaraju@googlemail.com
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title DataAccessOutput
#'
#' @description DataAccessOutput Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field access_level  character [optional]
#'
#' @field access_details  object [optional]
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
DataAccessOutput <- R6::R6Class(
  'DataAccessOutput',
  public = list(
    `access_level` = NULL,
    `access_details` = NULL,
    initialize = function(
        `access_level`=NULL, `access_details`=NULL, ...
    ) {
      local.optional.var <- list(...)
      if (!is.null(`access_level`)) {
        stopifnot(is.character(`access_level`), length(`access_level`) == 1)
        self$`access_level` <- `access_level`
      }
      if (!is.null(`access_details`)) {
        self$`access_details` <- `access_details`
      }
    },
    toJSON = function() {
      DataAccessOutputObject <- list()
      if (!is.null(self$`access_level`)) {
        DataAccessOutputObject[['access_level']] <-
          self$`access_level`
      }
      if (!is.null(self$`access_details`)) {
        DataAccessOutputObject[['access_details']] <-
          self$`access_details`
      }

      DataAccessOutputObject
    },
    fromJSON = function(DataAccessOutputJson) {
      DataAccessOutputObject <- jsonlite::fromJSON(DataAccessOutputJson)
      if (!is.null(DataAccessOutputObject$`access_level`)) {
        self$`access_level` <- DataAccessOutputObject$`access_level`
      }
      if (!is.null(DataAccessOutputObject$`access_details`)) {
        self$`access_details` <- DataAccessOutputObject$`access_details`
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`access_level`)) {
        sprintf(
        '"access_level":
          "%s"
                ',
        self$`access_level`
        )},
        if (!is.null(self$`access_details`)) {
        sprintf(
        '"access_details":
          "%s"
                ',
        self$`access_details`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(DataAccessOutputJson) {
      DataAccessOutputObject <- jsonlite::fromJSON(DataAccessOutputJson)
      self$`access_level` <- DataAccessOutputObject$`access_level`
      self$`access_details` <- DataAccessOutputObject$`access_details`
      self
    }
  )
)
