# F-UJI
#
# A Service for Evaluating Research Data Objects Based on <a href ='https://doi.org/10.5281/zenodo.3775793'>FAIRsFAIR Metrics</a>. <p> This work was supported by the <a href='https://www.fairsfair.eu/'>FAIRsFAIR</a> project (H2020-INFRAEOSC-2018-2020 Grant Agreement 831558).
#
# The version of the OpenAPI document: 1.1.0
# Contact: anusuriya.devaraju@googlemail.com
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title DataProvenanceOutputInner
#'
#' @description DataProvenanceOutputInner Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field is_available  character [optional]
#'
#' @field provenance_metadata  list( \link{map(character)} ) [optional]
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
DataProvenanceOutputInner <- R6::R6Class(
  'DataProvenanceOutputInner',
  public = list(
    `is_available` = NULL,
    `provenance_metadata` = NULL,
    initialize = function(
        `is_available`=TRUE, `provenance_metadata`=NULL, ...
    ) {
      local.optional.var <- list(...)
      if (!is.null(`is_available`)) {
        stopifnot(is.logical(`is_available`), length(`is_available`) == 1)
        self$`is_available` <- `is_available`
      }
      if (!is.null(`provenance_metadata`)) {
        stopifnot(is.vector(`provenance_metadata`), length(`provenance_metadata`) != 0)
        sapply(`provenance_metadata`, function(x) stopifnot(R6::is.R6(x)))
        self$`provenance_metadata` <- `provenance_metadata`
      }
    },
    toJSON = function() {
      DataProvenanceOutputInnerObject <- list()
      if (!is.null(self$`is_available`)) {
        DataProvenanceOutputInnerObject[['is_available']] <-
          self$`is_available`
      }
      if (!is.null(self$`provenance_metadata`)) {
        DataProvenanceOutputInnerObject[['provenance_metadata']] <-
          lapply(self$`provenance_metadata`, function(x) x$toJSON())
      }

      DataProvenanceOutputInnerObject
    },
    fromJSON = function(DataProvenanceOutputInnerJson) {
      DataProvenanceOutputInnerObject <- jsonlite::fromJSON(DataProvenanceOutputInnerJson)
      if (!is.null(DataProvenanceOutputInnerObject$`is_available`)) {
        self$`is_available` <- DataProvenanceOutputInnerObject$`is_available`
      }
      if (!is.null(DataProvenanceOutputInnerObject$`provenance_metadata`)) {
        self$`provenance_metadata` <- ApiClient$new()$deserializeObj(DataProvenanceOutputInnerObject$`provenance_metadata`, "array[map(character)]", loadNamespace("rfuji"))
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`is_available`)) {
        sprintf(
        '"is_available":
          %s
                ',
        tolower(self$`is_available`)
        )},
        if (!is.null(self$`provenance_metadata`)) {
        sprintf(
        '"provenance_metadata":
        [%s]
',
        paste(sapply(self$`provenance_metadata`, function(x) jsonlite::toJSON(x$toJSON(), auto_unbox=TRUE, digits = NA)), collapse=",")
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(DataProvenanceOutputInnerJson) {
      DataProvenanceOutputInnerObject <- jsonlite::fromJSON(DataProvenanceOutputInnerJson)
      self$`is_available` <- DataProvenanceOutputInnerObject$`is_available`
      self$`provenance_metadata` <- ApiClient$new()$deserializeObj(DataProvenanceOutputInnerObject$`provenance_metadata`, "array[map(character)]", loadNamespace("rfuji"))
      self
    }
  )
)
