# F-UJI
#
# A Service for Evaluating Research Data Objects Based on <a href ='https://doi.org/10.5281/zenodo.3775793'>FAIRsFAIR Metrics</a>. <p> This work was supported by the <a href='https://www.fairsfair.eu/'>FAIRsFAIR</a> project (H2020-INFRAEOSC-2018-2020 Grant Agreement 831558).
#
# The version of the OpenAPI document: 1.1.0
# Contact: anusuriya.devaraju@googlemail.com
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title DataFileFormatAllOf
#'
#' @description DataFileFormatAllOf Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field output  list( \link{DataFileFormatOutputInner} ) [optional]
#'
#' @field test_debug  list( character ) [optional]
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
DataFileFormatAllOf <- R6::R6Class(
  'DataFileFormatAllOf',
  public = list(
    `output` = NULL,
    `test_debug` = NULL,
    initialize = function(
        `output`=NULL, `test_debug`=NULL, ...
    ) {
      local.optional.var <- list(...)
      if (!is.null(`output`)) {
        stopifnot(is.vector(`output`), length(`output`) != 0)
        sapply(`output`, function(x) stopifnot(R6::is.R6(x)))
        self$`output` <- `output`
      }
      if (!is.null(`test_debug`)) {
        stopifnot(is.vector(`test_debug`), length(`test_debug`) != 0)
        sapply(`test_debug`, function(x) stopifnot(is.character(x)))
        self$`test_debug` <- `test_debug`
      }
    },
    toJSON = function() {
      DataFileFormatAllOfObject <- list()
      if (!is.null(self$`output`)) {
        DataFileFormatAllOfObject[['output']] <-
          lapply(self$`output`, function(x) x$toJSON())
      }
      if (!is.null(self$`test_debug`)) {
        DataFileFormatAllOfObject[['test_debug']] <-
          self$`test_debug`
      }

      DataFileFormatAllOfObject
    },
    fromJSON = function(DataFileFormatAllOfJson) {
      DataFileFormatAllOfObject <- jsonlite::fromJSON(DataFileFormatAllOfJson)
      if (!is.null(DataFileFormatAllOfObject$`output`)) {
        self$`output` <- ApiClient$new()$deserializeObj(DataFileFormatAllOfObject$`output`, "array[DataFileFormatOutputInner]", loadNamespace("rfuji"))
      }
      if (!is.null(DataFileFormatAllOfObject$`test_debug`)) {
        self$`test_debug` <- ApiClient$new()$deserializeObj(DataFileFormatAllOfObject$`test_debug`, "array[character]", loadNamespace("rfuji"))
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`output`)) {
        sprintf(
        '"output":
        [%s]
',
        paste(sapply(self$`output`, function(x) jsonlite::toJSON(x$toJSON(), auto_unbox=TRUE, digits = NA)), collapse=",")
        )},
        if (!is.null(self$`test_debug`)) {
        sprintf(
        '"test_debug":
           [%s]
        ',
        paste(unlist(lapply(self$`test_debug`, function(x) paste0('"', x, '"'))), collapse=",")
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(DataFileFormatAllOfJson) {
      DataFileFormatAllOfObject <- jsonlite::fromJSON(DataFileFormatAllOfJson)
      self$`output` <- ApiClient$new()$deserializeObj(DataFileFormatAllOfObject$`output`, "array[DataFileFormatOutputInner]", loadNamespace("rfuji"))
      self$`test_debug` <- ApiClient$new()$deserializeObj(DataFileFormatAllOfObject$`test_debug`, "array[character]", loadNamespace("rfuji"))
      self
    }
  )
)
