# F-UJI
#
# A Service for Evaluating Research Data Objects Based on <a href ='https://doi.org/10.5281/zenodo.3775793'>FAIRsFAIR Metrics</a>. <p> This work was supported by the <a href='https://www.fairsfair.eu/'>FAIRsFAIR</a> project (H2020-INFRAEOSC-2018-2020 Grant Agreement 831558).
#
# The version of the OpenAPI document: 1.1.0
# Contact: anusuriya.devaraju@googlemail.com
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title FormalMetadataOutputInner
#'
#' @description FormalMetadataOutputInner Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field serialization_format  character [optional]
#'
#' @field source  character [optional]
#'
#' @field is_metadata_found  character [optional]
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
FormalMetadataOutputInner <- R6::R6Class(
  'FormalMetadataOutputInner',
  public = list(
    `serialization_format` = NULL,
    `source` = NULL,
    `is_metadata_found` = NULL,
    initialize = function(
        `serialization_format`=NULL, `source`=NULL, `is_metadata_found`=FALSE, ...
    ) {
      local.optional.var <- list(...)
      if (!is.null(`serialization_format`)) {
        stopifnot(is.character(`serialization_format`), length(`serialization_format`) == 1)
        self$`serialization_format` <- `serialization_format`
      }
      if (!is.null(`source`)) {
        stopifnot(is.character(`source`), length(`source`) == 1)
        self$`source` <- `source`
      }
      if (!is.null(`is_metadata_found`)) {
        stopifnot(is.logical(`is_metadata_found`), length(`is_metadata_found`) == 1)
        self$`is_metadata_found` <- `is_metadata_found`
      }
    },
    toJSON = function() {
      FormalMetadataOutputInnerObject <- list()
      if (!is.null(self$`serialization_format`)) {
        FormalMetadataOutputInnerObject[['serialization_format']] <-
          self$`serialization_format`
      }
      if (!is.null(self$`source`)) {
        FormalMetadataOutputInnerObject[['source']] <-
          self$`source`
      }
      if (!is.null(self$`is_metadata_found`)) {
        FormalMetadataOutputInnerObject[['is_metadata_found']] <-
          self$`is_metadata_found`
      }

      FormalMetadataOutputInnerObject
    },
    fromJSON = function(FormalMetadataOutputInnerJson) {
      FormalMetadataOutputInnerObject <- jsonlite::fromJSON(FormalMetadataOutputInnerJson)
      if (!is.null(FormalMetadataOutputInnerObject$`serialization_format`)) {
        self$`serialization_format` <- FormalMetadataOutputInnerObject$`serialization_format`
      }
      if (!is.null(FormalMetadataOutputInnerObject$`source`)) {
        self$`source` <- FormalMetadataOutputInnerObject$`source`
      }
      if (!is.null(FormalMetadataOutputInnerObject$`is_metadata_found`)) {
        self$`is_metadata_found` <- FormalMetadataOutputInnerObject$`is_metadata_found`
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`serialization_format`)) {
        sprintf(
        '"serialization_format":
          "%s"
                ',
        self$`serialization_format`
        )},
        if (!is.null(self$`source`)) {
        sprintf(
        '"source":
          "%s"
                ',
        self$`source`
        )},
        if (!is.null(self$`is_metadata_found`)) {
        sprintf(
        '"is_metadata_found":
          %s
                ',
        tolower(self$`is_metadata_found`)
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(FormalMetadataOutputInnerJson) {
      FormalMetadataOutputInnerObject <- jsonlite::fromJSON(FormalMetadataOutputInnerJson)
      self$`serialization_format` <- FormalMetadataOutputInnerObject$`serialization_format`
      self$`source` <- FormalMetadataOutputInnerObject$`source`
      self$`is_metadata_found` <- FormalMetadataOutputInnerObject$`is_metadata_found`
      self
    }
  )
)
