# F-UJI
#
# A Service for Evaluating Research Data Objects Based on <a href ='https://doi.org/10.5281/zenodo.3775793'>FAIRsFAIR Metrics</a>. <p> This work was supported by the <a href='https://www.fairsfair.eu/'>FAIRsFAIR</a> project (H2020-INFRAEOSC-2018-2020 Grant Agreement 831558).
#
# The version of the OpenAPI document: 1.1.0
# Contact: anusuriya.devaraju@googlemail.com
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title IdentifierIncludedOutput
#'
#' @description IdentifierIncludedOutput Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field object_identifier_included  character [optional]
#'
#' @field content  list( \link{IdentifierIncludedOutputInner} ) [optional]
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
IdentifierIncludedOutput <- R6::R6Class(
  'IdentifierIncludedOutput',
  public = list(
    `object_identifier_included` = NULL,
    `content` = NULL,
    initialize = function(
        `object_identifier_included`=NULL, `content`=NULL, ...
    ) {
      local.optional.var <- list(...)
      if (!is.null(`object_identifier_included`)) {
        stopifnot(is.character(`object_identifier_included`), length(`object_identifier_included`) == 1)
        self$`object_identifier_included` <- `object_identifier_included`
      }
      if (!is.null(`content`)) {
        stopifnot(is.vector(`content`), length(`content`) != 0)
        sapply(`content`, function(x) stopifnot(R6::is.R6(x)))
        self$`content` <- `content`
      }
    },
    toJSON = function() {
      IdentifierIncludedOutputObject <- list()
      if (!is.null(self$`object_identifier_included`)) {
        IdentifierIncludedOutputObject[['object_identifier_included']] <-
          self$`object_identifier_included`
      }
      if (!is.null(self$`content`)) {
        IdentifierIncludedOutputObject[['content']] <-
          lapply(self$`content`, function(x) x$toJSON())
      }

      IdentifierIncludedOutputObject
    },
    fromJSON = function(IdentifierIncludedOutputJson) {
      IdentifierIncludedOutputObject <- jsonlite::fromJSON(IdentifierIncludedOutputJson)
      if (!is.null(IdentifierIncludedOutputObject$`object_identifier_included`)) {
        self$`object_identifier_included` <- IdentifierIncludedOutputObject$`object_identifier_included`
      }
      if (!is.null(IdentifierIncludedOutputObject$`content`)) {
        self$`content` <- ApiClient$new()$deserializeObj(IdentifierIncludedOutputObject$`content`, "array[IdentifierIncludedOutputInner]", loadNamespace("rfuji"))
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`object_identifier_included`)) {
        sprintf(
        '"object_identifier_included":
          "%s"
                ',
        self$`object_identifier_included`
        )},
        if (!is.null(self$`content`)) {
        sprintf(
        '"content":
        [%s]
',
        paste(sapply(self$`content`, function(x) jsonlite::toJSON(x$toJSON(), auto_unbox=TRUE, digits = NA)), collapse=",")
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(IdentifierIncludedOutputJson) {
      IdentifierIncludedOutputObject <- jsonlite::fromJSON(IdentifierIncludedOutputJson)
      self$`object_identifier_included` <- IdentifierIncludedOutputObject$`object_identifier_included`
      self$`content` <- ApiClient$new()$deserializeObj(IdentifierIncludedOutputObject$`content`, "array[IdentifierIncludedOutputInner]", loadNamespace("rfuji"))
      self
    }
  )
)
