# F-UJI
#
# A Service for Evaluating Research Data Objects Based on <a href ='https://doi.org/10.5281/zenodo.3775793'>FAIRsFAIR Metrics</a>. <p> This work was supported by the <a href='https://www.fairsfair.eu/'>FAIRsFAIR</a> project (H2020-INFRAEOSC-2018-2020 Grant Agreement 831558).
#
# The version of the OpenAPI document: 1.1.0
# Contact: anusuriya.devaraju@googlemail.com
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title IdentifierIncludedOutputInner
#'
#' @description IdentifierIncludedOutputInner Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field content_identifier_included  character [optional]
#'
#' @field content_identifier_active  character [optional]
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
IdentifierIncludedOutputInner <- R6::R6Class(
  'IdentifierIncludedOutputInner',
  public = list(
    `content_identifier_included` = NULL,
    `content_identifier_active` = NULL,
    initialize = function(
        `content_identifier_included`=NULL, `content_identifier_active`=FALSE, ...
    ) {
      local.optional.var <- list(...)
      if (!is.null(`content_identifier_included`)) {
        stopifnot(is.character(`content_identifier_included`), length(`content_identifier_included`) == 1)
        self$`content_identifier_included` <- `content_identifier_included`
      }
      if (!is.null(`content_identifier_active`)) {
        stopifnot(is.logical(`content_identifier_active`), length(`content_identifier_active`) == 1)
        self$`content_identifier_active` <- `content_identifier_active`
      }
    },
    toJSON = function() {
      IdentifierIncludedOutputInnerObject <- list()
      if (!is.null(self$`content_identifier_included`)) {
        IdentifierIncludedOutputInnerObject[['content_identifier_included']] <-
          self$`content_identifier_included`
      }
      if (!is.null(self$`content_identifier_active`)) {
        IdentifierIncludedOutputInnerObject[['content_identifier_active']] <-
          self$`content_identifier_active`
      }

      IdentifierIncludedOutputInnerObject
    },
    fromJSON = function(IdentifierIncludedOutputInnerJson) {
      IdentifierIncludedOutputInnerObject <- jsonlite::fromJSON(IdentifierIncludedOutputInnerJson)
      if (!is.null(IdentifierIncludedOutputInnerObject$`content_identifier_included`)) {
        self$`content_identifier_included` <- IdentifierIncludedOutputInnerObject$`content_identifier_included`
      }
      if (!is.null(IdentifierIncludedOutputInnerObject$`content_identifier_active`)) {
        self$`content_identifier_active` <- IdentifierIncludedOutputInnerObject$`content_identifier_active`
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`content_identifier_included`)) {
        sprintf(
        '"content_identifier_included":
          "%s"
                ',
        self$`content_identifier_included`
        )},
        if (!is.null(self$`content_identifier_active`)) {
        sprintf(
        '"content_identifier_active":
          %s
                ',
        tolower(self$`content_identifier_active`)
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(IdentifierIncludedOutputInnerJson) {
      IdentifierIncludedOutputInnerObject <- jsonlite::fromJSON(IdentifierIncludedOutputInnerJson)
      self$`content_identifier_included` <- IdentifierIncludedOutputInnerObject$`content_identifier_included`
      self$`content_identifier_active` <- IdentifierIncludedOutputInnerObject$`content_identifier_active`
      self
    }
  )
)
