# F-UJI
#
# A Service for Evaluating Research Data Objects Based on <a href ='https://doi.org/10.5281/zenodo.3775793'>FAIRsFAIR Metrics</a>. <p> This work was supported by the <a href='https://www.fairsfair.eu/'>FAIRsFAIR</a> project (H2020-INFRAEOSC-2018-2020 Grant Agreement 831558).
#
# The version of the OpenAPI document: 1.1.0
# Contact: anusuriya.devaraju@googlemail.com
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title LicenseOutputInner
#'
#' @description LicenseOutputInner Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field license  character [optional]
#'
#' @field OSI_approved  character [optional]
#'
#' @field details_url  character [optional]
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
LicenseOutputInner <- R6::R6Class(
  'LicenseOutputInner',
  public = list(
    `license` = NULL,
    `OSI_approved` = NULL,
    `details_url` = NULL,
    initialize = function(
        `license`=NULL, `OSI_approved`=FALSE, `details_url`=NULL, ...
    ) {
      local.optional.var <- list(...)
      if (!is.null(`license`)) {
        stopifnot(is.character(`license`), length(`license`) == 1)
        self$`license` <- `license`
      }
      if (!is.null(`OSI_approved`)) {
        stopifnot(is.logical(`OSI_approved`), length(`OSI_approved`) == 1)
        self$`OSI_approved` <- `OSI_approved`
      }
      if (!is.null(`details_url`)) {
        stopifnot(is.character(`details_url`), length(`details_url`) == 1)
        self$`details_url` <- `details_url`
      }
    },
    toJSON = function() {
      LicenseOutputInnerObject <- list()
      if (!is.null(self$`license`)) {
        LicenseOutputInnerObject[['license']] <-
          self$`license`
      }
      if (!is.null(self$`OSI_approved`)) {
        LicenseOutputInnerObject[['OSI_approved']] <-
          self$`OSI_approved`
      }
      if (!is.null(self$`details_url`)) {
        LicenseOutputInnerObject[['details_url']] <-
          self$`details_url`
      }

      LicenseOutputInnerObject
    },
    fromJSON = function(LicenseOutputInnerJson) {
      LicenseOutputInnerObject <- jsonlite::fromJSON(LicenseOutputInnerJson)
      if (!is.null(LicenseOutputInnerObject$`license`)) {
        self$`license` <- LicenseOutputInnerObject$`license`
      }
      if (!is.null(LicenseOutputInnerObject$`OSI_approved`)) {
        self$`OSI_approved` <- LicenseOutputInnerObject$`OSI_approved`
      }
      if (!is.null(LicenseOutputInnerObject$`details_url`)) {
        self$`details_url` <- LicenseOutputInnerObject$`details_url`
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`license`)) {
        sprintf(
        '"license":
          "%s"
                ',
        self$`license`
        )},
        if (!is.null(self$`OSI_approved`)) {
        sprintf(
        '"OSI_approved":
          %s
                ',
        tolower(self$`OSI_approved`)
        )},
        if (!is.null(self$`details_url`)) {
        sprintf(
        '"details_url":
          "%s"
                ',
        self$`details_url`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(LicenseOutputInnerJson) {
      LicenseOutputInnerObject <- jsonlite::fromJSON(LicenseOutputInnerJson)
      self$`license` <- LicenseOutputInnerObject$`license`
      self$`OSI_approved` <- LicenseOutputInnerObject$`OSI_approved`
      self$`details_url` <- LicenseOutputInnerObject$`details_url`
      self
    }
  )
)
