# F-UJI
#
# A Service for Evaluating Research Data Objects Based on <a href ='https://doi.org/10.5281/zenodo.3775793'>FAIRsFAIR Metrics</a>. <p> This work was supported by the <a href='https://www.fairsfair.eu/'>FAIRsFAIR</a> project (H2020-INFRAEOSC-2018-2020 Grant Agreement 831558).
#
# The version of the OpenAPI document: 1.1.0
# Contact: anusuriya.devaraju@googlemail.com
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title License
#'
#' @description License Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field id  integer 
#'
#' @field metric_identifier  character 
#'
#' @field metric_name  character 
#'
#' @field metric_tests  named list( \link{FAIRResultEvaluationCriterium} ) [optional]
#'
#' @field test_status  character 
#'
#' @field score  \link{FAIRResultCommonScore} 
#'
#' @field maturity  character [optional]
#'
#' @field output  list( \link{LicenseOutputInner} ) [optional]
#'
#' @field test_debug  list( character ) [optional]
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
License <- R6::R6Class(
  'License',
  public = list(
    `id` = NULL,
    `metric_identifier` = NULL,
    `metric_name` = NULL,
    `metric_tests` = NULL,
    `test_status` = NULL,
    `score` = NULL,
    `maturity` = NULL,
    `output` = NULL,
    `test_debug` = NULL,
    initialize = function(
        `id`, `metric_identifier`, `metric_name`, `test_status`, `score`, `metric_tests`=NULL, `maturity`='incomplete', `output`=NULL, `test_debug`=NULL, ...
    ) {
      local.optional.var <- list(...)
      if (!missing(`id`)) {
        stopifnot(is.numeric(`id`), length(`id`) == 1)
        self$`id` <- `id`
      }
      if (!missing(`metric_identifier`)) {
        stopifnot(is.character(`metric_identifier`), length(`metric_identifier`) == 1)
        self$`metric_identifier` <- `metric_identifier`
      }
      if (!missing(`metric_name`)) {
        stopifnot(is.character(`metric_name`), length(`metric_name`) == 1)
        self$`metric_name` <- `metric_name`
      }
      if (!missing(`test_status`)) {
        stopifnot(is.character(`test_status`), length(`test_status`) == 1)
        self$`test_status` <- `test_status`
      }
      if (!missing(`score`)) {
        stopifnot(R6::is.R6(`score`))
        self$`score` <- `score`
      }
      if (!is.null(`metric_tests`)) {
        stopifnot(is.vector(`metric_tests`), length(`metric_tests`) != 0)
        sapply(`metric_tests`, function(x) stopifnot(R6::is.R6(x)))
        self$`metric_tests` <- `metric_tests`
      }
      if (!is.null(`maturity`)) {
        stopifnot(is.character(`maturity`), length(`maturity`) == 1)
        self$`maturity` <- `maturity`
      }
      if (!is.null(`output`)) {
        stopifnot(is.vector(`output`), length(`output`) != 0)
        sapply(`output`, function(x) stopifnot(R6::is.R6(x)))
        self$`output` <- `output`
      }
      if (!is.null(`test_debug`)) {
        stopifnot(is.vector(`test_debug`), length(`test_debug`) != 0)
        sapply(`test_debug`, function(x) stopifnot(is.character(x)))
        self$`test_debug` <- `test_debug`
      }
    },
    toJSON = function() {
      LicenseObject <- list()
      if (!is.null(self$`id`)) {
        LicenseObject[['id']] <-
          self$`id`
      }
      if (!is.null(self$`metric_identifier`)) {
        LicenseObject[['metric_identifier']] <-
          self$`metric_identifier`
      }
      if (!is.null(self$`metric_name`)) {
        LicenseObject[['metric_name']] <-
          self$`metric_name`
      }
      if (!is.null(self$`metric_tests`)) {
        LicenseObject[['metric_tests']] <-
          lapply(self$`metric_tests`, function(x) x$toJSON())
      }
      if (!is.null(self$`test_status`)) {
        LicenseObject[['test_status']] <-
          self$`test_status`
      }
      if (!is.null(self$`score`)) {
        LicenseObject[['score']] <-
          self$`score`$toJSON()
      }
      if (!is.null(self$`maturity`)) {
        LicenseObject[['maturity']] <-
          self$`maturity`
      }
      if (!is.null(self$`output`)) {
        LicenseObject[['output']] <-
          lapply(self$`output`, function(x) x$toJSON())
      }
      if (!is.null(self$`test_debug`)) {
        LicenseObject[['test_debug']] <-
          self$`test_debug`
      }

      LicenseObject
    },
    fromJSON = function(LicenseJson) {
      LicenseObject <- jsonlite::fromJSON(LicenseJson)
      if (!is.null(LicenseObject$`id`)) {
        self$`id` <- LicenseObject$`id`
      }
      if (!is.null(LicenseObject$`metric_identifier`)) {
        self$`metric_identifier` <- LicenseObject$`metric_identifier`
      }
      if (!is.null(LicenseObject$`metric_name`)) {
        self$`metric_name` <- LicenseObject$`metric_name`
      }
      if (!is.null(LicenseObject$`metric_tests`)) {
        self$`metric_tests` <- ApiClient$new()$deserializeObj(LicenseObject$`metric_tests`, "map(FAIRResultEvaluationCriterium)", loadNamespace("rfuji"))
      }
      if (!is.null(LicenseObject$`test_status`)) {
        self$`test_status` <- LicenseObject$`test_status`
      }
      if (!is.null(LicenseObject$`score`)) {
        scoreObject <- FAIRResultCommonScore$new()
        scoreObject$fromJSON(jsonlite::toJSON(LicenseObject$score, auto_unbox = TRUE, digits = NA))
        self$`score` <- scoreObject
      }
      if (!is.null(LicenseObject$`maturity`)) {
        self$`maturity` <- LicenseObject$`maturity`
      }
      if (!is.null(LicenseObject$`output`)) {
        self$`output` <- ApiClient$new()$deserializeObj(LicenseObject$`output`, "array[LicenseOutputInner]", loadNamespace("rfuji"))
      }
      if (!is.null(LicenseObject$`test_debug`)) {
        self$`test_debug` <- ApiClient$new()$deserializeObj(LicenseObject$`test_debug`, "array[character]", loadNamespace("rfuji"))
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`id`)) {
        sprintf(
        '"id":
          %d
                ',
        self$`id`
        )},
        if (!is.null(self$`metric_identifier`)) {
        sprintf(
        '"metric_identifier":
          "%s"
                ',
        self$`metric_identifier`
        )},
        if (!is.null(self$`metric_name`)) {
        sprintf(
        '"metric_name":
          "%s"
                ',
        self$`metric_name`
        )},
        if (!is.null(self$`metric_tests`)) {
        sprintf(
        '"metric_tests":
        %s
',
        jsonlite::toJSON(lapply(self$`metric_tests`, function(x){ x$toJSON() }), auto_unbox = TRUE, digits=NA)
        )},
        if (!is.null(self$`test_status`)) {
        sprintf(
        '"test_status":
          "%s"
                ',
        self$`test_status`
        )},
        if (!is.null(self$`score`)) {
        sprintf(
        '"score":
        %s
        ',
        jsonlite::toJSON(self$`score`$toJSON(), auto_unbox=TRUE, digits = NA)
        )},
        if (!is.null(self$`maturity`)) {
        sprintf(
        '"maturity":
          "%s"
                ',
        self$`maturity`
        )},
        if (!is.null(self$`output`)) {
        sprintf(
        '"output":
        [%s]
',
        paste(sapply(self$`output`, function(x) jsonlite::toJSON(x$toJSON(), auto_unbox=TRUE, digits = NA)), collapse=",")
        )},
        if (!is.null(self$`test_debug`)) {
        sprintf(
        '"test_debug":
           [%s]
        ',
        paste(unlist(lapply(self$`test_debug`, function(x) paste0('"', x, '"'))), collapse=",")
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(LicenseJson) {
      LicenseObject <- jsonlite::fromJSON(LicenseJson)
      self$`id` <- LicenseObject$`id`
      self$`metric_identifier` <- LicenseObject$`metric_identifier`
      self$`metric_name` <- LicenseObject$`metric_name`
      self$`metric_tests` <- ApiClient$new()$deserializeObj(LicenseObject$`metric_tests`, "map(FAIRResultEvaluationCriterium)", loadNamespace("rfuji"))
      self$`test_status` <- LicenseObject$`test_status`
      self$`score` <- FAIRResultCommonScore$new()$fromJSON(jsonlite::toJSON(LicenseObject$score, auto_unbox = TRUE, digits = NA))
      self$`maturity` <- LicenseObject$`maturity`
      self$`output` <- ApiClient$new()$deserializeObj(LicenseObject$`output`, "array[LicenseOutputInner]", loadNamespace("rfuji"))
      self$`test_debug` <- ApiClient$new()$deserializeObj(LicenseObject$`test_debug`, "array[character]", loadNamespace("rfuji"))
      self
    }
  )
)
