# F-UJI
#
# A Service for Evaluating Research Data Objects Based on <a href ='https://doi.org/10.5281/zenodo.3775793'>FAIRsFAIR Metrics</a>. <p> This work was supported by the <a href='https://www.fairsfair.eu/'>FAIRsFAIR</a> project (H2020-INFRAEOSC-2018-2020 Grant Agreement 831558).
#
# The version of the OpenAPI document: 1.1.0
# Contact: anusuriya.devaraju@googlemail.com
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title MetadataPreservedOutput
#'
#' @description MetadataPreservedOutput Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field metadata_preservation_method  list( character ) [optional]
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
MetadataPreservedOutput <- R6::R6Class(
  'MetadataPreservedOutput',
  public = list(
    `metadata_preservation_method` = NULL,
    initialize = function(
        `metadata_preservation_method`=NULL, ...
    ) {
      local.optional.var <- list(...)
      if (!is.null(`metadata_preservation_method`)) {
        stopifnot(is.vector(`metadata_preservation_method`), length(`metadata_preservation_method`) != 0)
        sapply(`metadata_preservation_method`, function(x) stopifnot(is.character(x)))
        self$`metadata_preservation_method` <- `metadata_preservation_method`
      }
    },
    toJSON = function() {
      MetadataPreservedOutputObject <- list()
      if (!is.null(self$`metadata_preservation_method`)) {
        MetadataPreservedOutputObject[['metadata_preservation_method']] <-
          self$`metadata_preservation_method`
      }

      MetadataPreservedOutputObject
    },
    fromJSON = function(MetadataPreservedOutputJson) {
      MetadataPreservedOutputObject <- jsonlite::fromJSON(MetadataPreservedOutputJson)
      if (!is.null(MetadataPreservedOutputObject$`metadata_preservation_method`)) {
        self$`metadata_preservation_method` <- ApiClient$new()$deserializeObj(MetadataPreservedOutputObject$`metadata_preservation_method`, "array[character]", loadNamespace("rfuji"))
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`metadata_preservation_method`)) {
        sprintf(
        '"metadata_preservation_method":
           [%s]
        ',
        paste(unlist(lapply(self$`metadata_preservation_method`, function(x) paste0('"', x, '"'))), collapse=",")
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(MetadataPreservedOutputJson) {
      MetadataPreservedOutputObject <- jsonlite::fromJSON(MetadataPreservedOutputJson)
      self$`metadata_preservation_method` <- ApiClient$new()$deserializeObj(MetadataPreservedOutputObject$`metadata_preservation_method`, "array[character]", loadNamespace("rfuji"))
      self
    }
  )
)
