# F-UJI
#
# A Service for Evaluating Research Data Objects Based on <a href ='https://doi.org/10.5281/zenodo.3775793'>FAIRsFAIR Metrics</a>. <p> This work was supported by the <a href='https://www.fairsfair.eu/'>FAIRsFAIR</a> project (H2020-INFRAEOSC-2018-2020 Grant Agreement 831558).
#
# The version of the OpenAPI document: 1.1.0
# Contact: anusuriya.devaraju@googlemail.com
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title Metrics
#'
#' @description Metrics Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field total  integer [optional]
#'
#' @field metrics  list( \link{Metric} ) [optional]
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
Metrics <- R6::R6Class(
  'Metrics',
  public = list(
    `total` = NULL,
    `metrics` = NULL,
    initialize = function(
        `total`=NULL, `metrics`=NULL, ...
    ) {
      local.optional.var <- list(...)
      if (!is.null(`total`)) {
        stopifnot(is.numeric(`total`), length(`total`) == 1)
        self$`total` <- `total`
      }
      if (!is.null(`metrics`)) {
        stopifnot(is.vector(`metrics`), length(`metrics`) != 0)
        sapply(`metrics`, function(x) stopifnot(R6::is.R6(x)))
        self$`metrics` <- `metrics`
      }
    },
    toJSON = function() {
      MetricsObject <- list()
      if (!is.null(self$`total`)) {
        MetricsObject[['total']] <-
          self$`total`
      }
      if (!is.null(self$`metrics`)) {
        MetricsObject[['metrics']] <-
          lapply(self$`metrics`, function(x) x$toJSON())
      }

      MetricsObject
    },
    fromJSON = function(MetricsJson) {
      MetricsObject <- jsonlite::fromJSON(MetricsJson)
      if (!is.null(MetricsObject$`total`)) {
        self$`total` <- MetricsObject$`total`
      }
      if (!is.null(MetricsObject$`metrics`)) {
        self$`metrics` <- ApiClient$new()$deserializeObj(MetricsObject$`metrics`, "array[Metric]", loadNamespace("rfuji"))
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`total`)) {
        sprintf(
        '"total":
          %d
                ',
        self$`total`
        )},
        if (!is.null(self$`metrics`)) {
        sprintf(
        '"metrics":
        [%s]
',
        paste(sapply(self$`metrics`, function(x) jsonlite::toJSON(x$toJSON(), auto_unbox=TRUE, digits = NA)), collapse=",")
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(MetricsJson) {
      MetricsObject <- jsonlite::fromJSON(MetricsJson)
      self$`total` <- MetricsObject$`total`
      self$`metrics` <- ApiClient$new()$deserializeObj(MetricsObject$`metrics`, "array[Metric]", loadNamespace("rfuji"))
      self
    }
  )
)
