# F-UJI
#
# A Service for Evaluating Research Data Objects Based on <a href ='https://doi.org/10.5281/zenodo.3775793'>FAIRsFAIR Metrics</a>. <p> This work was supported by the <a href='https://www.fairsfair.eu/'>FAIRsFAIR</a> project (H2020-INFRAEOSC-2018-2020 Grant Agreement 831558).
#
# The version of the OpenAPI document: 1.1.0
# Contact: anusuriya.devaraju@googlemail.com
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title Metric
#'
#' @description Metric Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field metric_identifier  character [optional]
#'
#' @field metric_name  character [optional]
#'
#' @field description  character [optional]
#'
#' @field fair_principle  character [optional]
#'
#' @field evaluation_mechanism  character [optional]
#'
#' @field date_created  character [optional]
#'
#' @field date_updated  character [optional]
#'
#' @field created_by  character [optional]
#'
#' @field version  numeric [optional]
#'
#' @field total_score  integer [optional]
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
Metric <- R6::R6Class(
  'Metric',
  public = list(
    `metric_identifier` = NULL,
    `metric_name` = NULL,
    `description` = NULL,
    `fair_principle` = NULL,
    `evaluation_mechanism` = NULL,
    `date_created` = NULL,
    `date_updated` = NULL,
    `created_by` = NULL,
    `version` = NULL,
    `total_score` = NULL,
    initialize = function(
        `metric_identifier`=NULL, `metric_name`=NULL, `description`=NULL, `fair_principle`=NULL, `evaluation_mechanism`=NULL, `date_created`=NULL, `date_updated`=NULL, `created_by`=NULL, `version`=NULL, `total_score`=NULL, ...
    ) {
      local.optional.var <- list(...)
      if (!is.null(`metric_identifier`)) {
        stopifnot(is.character(`metric_identifier`), length(`metric_identifier`) == 1)
        self$`metric_identifier` <- `metric_identifier`
      }
      if (!is.null(`metric_name`)) {
        stopifnot(is.character(`metric_name`), length(`metric_name`) == 1)
        self$`metric_name` <- `metric_name`
      }
      if (!is.null(`description`)) {
        stopifnot(is.character(`description`), length(`description`) == 1)
        self$`description` <- `description`
      }
      if (!is.null(`fair_principle`)) {
        stopifnot(is.character(`fair_principle`), length(`fair_principle`) == 1)
        self$`fair_principle` <- `fair_principle`
      }
      if (!is.null(`evaluation_mechanism`)) {
        stopifnot(is.character(`evaluation_mechanism`), length(`evaluation_mechanism`) == 1)
        self$`evaluation_mechanism` <- `evaluation_mechanism`
      }
      if (!is.null(`date_created`)) {
        stopifnot(is.character(`date_created`), length(`date_created`) == 1)
        self$`date_created` <- `date_created`
      }
      if (!is.null(`date_updated`)) {
        stopifnot(is.character(`date_updated`), length(`date_updated`) == 1)
        self$`date_updated` <- `date_updated`
      }
      if (!is.null(`created_by`)) {
        stopifnot(is.character(`created_by`), length(`created_by`) == 1)
        self$`created_by` <- `created_by`
      }
      if (!is.null(`version`)) {
        stopifnot(is.numeric(`version`), length(`version`) == 1)
        self$`version` <- `version`
      }
      if (!is.null(`total_score`)) {
        stopifnot(is.numeric(`total_score`), length(`total_score`) == 1)
        self$`total_score` <- `total_score`
      }
    },
    toJSON = function() {
      MetricObject <- list()
      if (!is.null(self$`metric_identifier`)) {
        MetricObject[['metric_identifier']] <-
          self$`metric_identifier`
      }
      if (!is.null(self$`metric_name`)) {
        MetricObject[['metric_name']] <-
          self$`metric_name`
      }
      if (!is.null(self$`description`)) {
        MetricObject[['description']] <-
          self$`description`
      }
      if (!is.null(self$`fair_principle`)) {
        MetricObject[['fair_principle']] <-
          self$`fair_principle`
      }
      if (!is.null(self$`evaluation_mechanism`)) {
        MetricObject[['evaluation_mechanism']] <-
          self$`evaluation_mechanism`
      }
      if (!is.null(self$`date_created`)) {
        MetricObject[['date_created']] <-
          self$`date_created`
      }
      if (!is.null(self$`date_updated`)) {
        MetricObject[['date_updated']] <-
          self$`date_updated`
      }
      if (!is.null(self$`created_by`)) {
        MetricObject[['created_by']] <-
          self$`created_by`
      }
      if (!is.null(self$`version`)) {
        MetricObject[['version']] <-
          self$`version`
      }
      if (!is.null(self$`total_score`)) {
        MetricObject[['total_score']] <-
          self$`total_score`
      }

      MetricObject
    },
    fromJSON = function(MetricJson) {
      MetricObject <- jsonlite::fromJSON(MetricJson)
      if (!is.null(MetricObject$`metric_identifier`)) {
        self$`metric_identifier` <- MetricObject$`metric_identifier`
      }
      if (!is.null(MetricObject$`metric_name`)) {
        self$`metric_name` <- MetricObject$`metric_name`
      }
      if (!is.null(MetricObject$`description`)) {
        self$`description` <- MetricObject$`description`
      }
      if (!is.null(MetricObject$`fair_principle`)) {
        self$`fair_principle` <- MetricObject$`fair_principle`
      }
      if (!is.null(MetricObject$`evaluation_mechanism`)) {
        self$`evaluation_mechanism` <- MetricObject$`evaluation_mechanism`
      }
      if (!is.null(MetricObject$`date_created`)) {
        self$`date_created` <- MetricObject$`date_created`
      }
      if (!is.null(MetricObject$`date_updated`)) {
        self$`date_updated` <- MetricObject$`date_updated`
      }
      if (!is.null(MetricObject$`created_by`)) {
        self$`created_by` <- MetricObject$`created_by`
      }
      if (!is.null(MetricObject$`version`)) {
        self$`version` <- MetricObject$`version`
      }
      if (!is.null(MetricObject$`total_score`)) {
        self$`total_score` <- MetricObject$`total_score`
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`metric_identifier`)) {
        sprintf(
        '"metric_identifier":
          "%s"
                ',
        self$`metric_identifier`
        )},
        if (!is.null(self$`metric_name`)) {
        sprintf(
        '"metric_name":
          "%s"
                ',
        self$`metric_name`
        )},
        if (!is.null(self$`description`)) {
        sprintf(
        '"description":
          "%s"
                ',
        self$`description`
        )},
        if (!is.null(self$`fair_principle`)) {
        sprintf(
        '"fair_principle":
          "%s"
                ',
        self$`fair_principle`
        )},
        if (!is.null(self$`evaluation_mechanism`)) {
        sprintf(
        '"evaluation_mechanism":
          "%s"
                ',
        self$`evaluation_mechanism`
        )},
        if (!is.null(self$`date_created`)) {
        sprintf(
        '"date_created":
          "%s"
                ',
        self$`date_created`
        )},
        if (!is.null(self$`date_updated`)) {
        sprintf(
        '"date_updated":
          "%s"
                ',
        self$`date_updated`
        )},
        if (!is.null(self$`created_by`)) {
        sprintf(
        '"created_by":
          "%s"
                ',
        self$`created_by`
        )},
        if (!is.null(self$`version`)) {
        sprintf(
        '"version":
          %d
                ',
        self$`version`
        )},
        if (!is.null(self$`total_score`)) {
        sprintf(
        '"total_score":
          %d
                ',
        self$`total_score`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(MetricJson) {
      MetricObject <- jsonlite::fromJSON(MetricJson)
      self$`metric_identifier` <- MetricObject$`metric_identifier`
      self$`metric_name` <- MetricObject$`metric_name`
      self$`description` <- MetricObject$`description`
      self$`fair_principle` <- MetricObject$`fair_principle`
      self$`evaluation_mechanism` <- MetricObject$`evaluation_mechanism`
      self$`date_created` <- MetricObject$`date_created`
      self$`date_updated` <- MetricObject$`date_updated`
      self$`created_by` <- MetricObject$`created_by`
      self$`version` <- MetricObject$`version`
      self$`total_score` <- MetricObject$`total_score`
      self
    }
  )
)
