# F-UJI
#
# A Service for Evaluating Research Data Objects Based on <a href ='https://doi.org/10.5281/zenodo.3775793'>FAIRsFAIR Metrics</a>. <p> This work was supported by the <a href='https://www.fairsfair.eu/'>FAIRsFAIR</a> project (H2020-INFRAEOSC-2018-2020 Grant Agreement 831558).
#
# The version of the OpenAPI document: 1.1.0
# Contact: anusuriya.devaraju@googlemail.com
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title OutputSearchMechanisms
#'
#' @description OutputSearchMechanisms Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field mechanism  character [optional]
#'
#' @field mechanism_info  list( character ) [optional]
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
OutputSearchMechanisms <- R6::R6Class(
  'OutputSearchMechanisms',
  public = list(
    `mechanism` = NULL,
    `mechanism_info` = NULL,
    initialize = function(
        `mechanism`=NULL, `mechanism_info`=NULL, ...
    ) {
      local.optional.var <- list(...)
      if (!is.null(`mechanism`)) {
        stopifnot(is.character(`mechanism`), length(`mechanism`) == 1)
        self$`mechanism` <- `mechanism`
      }
      if (!is.null(`mechanism_info`)) {
        stopifnot(is.vector(`mechanism_info`), length(`mechanism_info`) != 0)
        sapply(`mechanism_info`, function(x) stopifnot(is.character(x)))
        self$`mechanism_info` <- `mechanism_info`
      }
    },
    toJSON = function() {
      OutputSearchMechanismsObject <- list()
      if (!is.null(self$`mechanism`)) {
        OutputSearchMechanismsObject[['mechanism']] <-
          self$`mechanism`
      }
      if (!is.null(self$`mechanism_info`)) {
        OutputSearchMechanismsObject[['mechanism_info']] <-
          self$`mechanism_info`
      }

      OutputSearchMechanismsObject
    },
    fromJSON = function(OutputSearchMechanismsJson) {
      OutputSearchMechanismsObject <- jsonlite::fromJSON(OutputSearchMechanismsJson)
      if (!is.null(OutputSearchMechanismsObject$`mechanism`)) {
        self$`mechanism` <- OutputSearchMechanismsObject$`mechanism`
      }
      if (!is.null(OutputSearchMechanismsObject$`mechanism_info`)) {
        self$`mechanism_info` <- ApiClient$new()$deserializeObj(OutputSearchMechanismsObject$`mechanism_info`, "array[character]", loadNamespace("rfuji"))
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`mechanism`)) {
        sprintf(
        '"mechanism":
          "%s"
                ',
        self$`mechanism`
        )},
        if (!is.null(self$`mechanism_info`)) {
        sprintf(
        '"mechanism_info":
           [%s]
        ',
        paste(unlist(lapply(self$`mechanism_info`, function(x) paste0('"', x, '"'))), collapse=",")
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(OutputSearchMechanismsJson) {
      OutputSearchMechanismsObject <- jsonlite::fromJSON(OutputSearchMechanismsJson)
      self$`mechanism` <- OutputSearchMechanismsObject$`mechanism`
      self$`mechanism_info` <- ApiClient$new()$deserializeObj(OutputSearchMechanismsObject$`mechanism_info`, "array[character]", loadNamespace("rfuji"))
      self
    }
  )
)
