# F-UJI
#
# A Service for Evaluating Research Data Objects Based on <a href ='https://doi.org/10.5281/zenodo.3775793'>FAIRsFAIR Metrics</a>. <p> This work was supported by the <a href='https://www.fairsfair.eu/'>FAIRsFAIR</a> project (H2020-INFRAEOSC-2018-2020 Grant Agreement 831558).
#
# The version of the OpenAPI document: 1.1.0
# Contact: anusuriya.devaraju@googlemail.com
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title OutputCoreMetadataFound
#'
#' @description OutputCoreMetadataFound Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field creator  list( character ) 
#'
#' @field title  character 
#'
#' @field publisher  character 
#'
#' @field publication_date  character 
#'
#' @field summary  character 
#'
#' @field keywords  character 
#'
#' @field object_identifier  character 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
OutputCoreMetadataFound <- R6::R6Class(
  'OutputCoreMetadataFound',
  public = list(
    `creator` = NULL,
    `title` = NULL,
    `publisher` = NULL,
    `publication_date` = NULL,
    `summary` = NULL,
    `keywords` = NULL,
    `object_identifier` = NULL,
    initialize = function(
        `creator`, `title`, `publisher`, `publication_date`, `summary`, `keywords`, `object_identifier`, ...
    ) {
      local.optional.var <- list(...)
      if (!missing(`creator`)) {
        stopifnot(is.vector(`creator`), length(`creator`) != 0)
        sapply(`creator`, function(x) stopifnot(is.character(x)))
        self$`creator` <- `creator`
      }
      if (!missing(`title`)) {
        stopifnot(is.character(`title`), length(`title`) == 1)
        self$`title` <- `title`
      }
      if (!missing(`publisher`)) {
        stopifnot(is.character(`publisher`), length(`publisher`) == 1)
        self$`publisher` <- `publisher`
      }
      if (!missing(`publication_date`)) {
        stopifnot(is.character(`publication_date`), length(`publication_date`) == 1)
        self$`publication_date` <- `publication_date`
      }
      if (!missing(`summary`)) {
        stopifnot(is.character(`summary`), length(`summary`) == 1)
        self$`summary` <- `summary`
      }
      if (!missing(`keywords`)) {
        stopifnot(is.character(`keywords`), length(`keywords`) == 1)
        self$`keywords` <- `keywords`
      }
      if (!missing(`object_identifier`)) {
        stopifnot(is.character(`object_identifier`), length(`object_identifier`) == 1)
        self$`object_identifier` <- `object_identifier`
      }
    },
    toJSON = function() {
      OutputCoreMetadataFoundObject <- list()
      if (!is.null(self$`creator`)) {
        OutputCoreMetadataFoundObject[['creator']] <-
          self$`creator`
      }
      if (!is.null(self$`title`)) {
        OutputCoreMetadataFoundObject[['title']] <-
          self$`title`
      }
      if (!is.null(self$`publisher`)) {
        OutputCoreMetadataFoundObject[['publisher']] <-
          self$`publisher`
      }
      if (!is.null(self$`publication_date`)) {
        OutputCoreMetadataFoundObject[['publication_date']] <-
          self$`publication_date`
      }
      if (!is.null(self$`summary`)) {
        OutputCoreMetadataFoundObject[['summary']] <-
          self$`summary`
      }
      if (!is.null(self$`keywords`)) {
        OutputCoreMetadataFoundObject[['keywords']] <-
          self$`keywords`
      }
      if (!is.null(self$`object_identifier`)) {
        OutputCoreMetadataFoundObject[['object_identifier']] <-
          self$`object_identifier`
      }

      OutputCoreMetadataFoundObject
    },
    fromJSON = function(OutputCoreMetadataFoundJson) {
      OutputCoreMetadataFoundObject <- jsonlite::fromJSON(OutputCoreMetadataFoundJson)
      if (!is.null(OutputCoreMetadataFoundObject$`creator`)) {
        self$`creator` <- ApiClient$new()$deserializeObj(OutputCoreMetadataFoundObject$`creator`, "array[character]", loadNamespace("rfuji"))
      }
      if (!is.null(OutputCoreMetadataFoundObject$`title`)) {
        self$`title` <- OutputCoreMetadataFoundObject$`title`
      }
      if (!is.null(OutputCoreMetadataFoundObject$`publisher`)) {
        self$`publisher` <- OutputCoreMetadataFoundObject$`publisher`
      }
      if (!is.null(OutputCoreMetadataFoundObject$`publication_date`)) {
        self$`publication_date` <- OutputCoreMetadataFoundObject$`publication_date`
      }
      if (!is.null(OutputCoreMetadataFoundObject$`summary`)) {
        self$`summary` <- OutputCoreMetadataFoundObject$`summary`
      }
      if (!is.null(OutputCoreMetadataFoundObject$`keywords`)) {
        self$`keywords` <- OutputCoreMetadataFoundObject$`keywords`
      }
      if (!is.null(OutputCoreMetadataFoundObject$`object_identifier`)) {
        self$`object_identifier` <- OutputCoreMetadataFoundObject$`object_identifier`
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`creator`)) {
        sprintf(
        '"creator":
           [%s]
        ',
        paste(unlist(lapply(self$`creator`, function(x) paste0('"', x, '"'))), collapse=",")
        )},
        if (!is.null(self$`title`)) {
        sprintf(
        '"title":
          "%s"
                ',
        self$`title`
        )},
        if (!is.null(self$`publisher`)) {
        sprintf(
        '"publisher":
          "%s"
                ',
        self$`publisher`
        )},
        if (!is.null(self$`publication_date`)) {
        sprintf(
        '"publication_date":
          "%s"
                ',
        self$`publication_date`
        )},
        if (!is.null(self$`summary`)) {
        sprintf(
        '"summary":
          "%s"
                ',
        self$`summary`
        )},
        if (!is.null(self$`keywords`)) {
        sprintf(
        '"keywords":
          "%s"
                ',
        self$`keywords`
        )},
        if (!is.null(self$`object_identifier`)) {
        sprintf(
        '"object_identifier":
          "%s"
                ',
        self$`object_identifier`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(OutputCoreMetadataFoundJson) {
      OutputCoreMetadataFoundObject <- jsonlite::fromJSON(OutputCoreMetadataFoundJson)
      self$`creator` <- ApiClient$new()$deserializeObj(OutputCoreMetadataFoundObject$`creator`, "array[character]", loadNamespace("rfuji"))
      self$`title` <- OutputCoreMetadataFoundObject$`title`
      self$`publisher` <- OutputCoreMetadataFoundObject$`publisher`
      self$`publication_date` <- OutputCoreMetadataFoundObject$`publication_date`
      self$`summary` <- OutputCoreMetadataFoundObject$`summary`
      self$`keywords` <- OutputCoreMetadataFoundObject$`keywords`
      self$`object_identifier` <- OutputCoreMetadataFoundObject$`object_identifier`
      self
    }
  )
)
