# F-UJI
#
# A Service for Evaluating Research Data Objects Based on <a href ='https://doi.org/10.5281/zenodo.3775793'>FAIRsFAIR Metrics</a>. <p> This work was supported by the <a href='https://www.fairsfair.eu/'>FAIRsFAIR</a> project (H2020-INFRAEOSC-2018-2020 Grant Agreement 831558).
#
# The version of the OpenAPI document: 1.1.0
# Contact: anusuriya.devaraju@googlemail.com
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title PersistenceOutput
#'
#' @description PersistenceOutput Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field pid  character [optional]
#'
#' @field pid_scheme  character [optional]
#'
#' @field resolvable_status  character [optional]
#'
#' @field resolved_url  character [optional]
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
PersistenceOutput <- R6::R6Class(
  'PersistenceOutput',
  public = list(
    `pid` = NULL,
    `pid_scheme` = NULL,
    `resolvable_status` = NULL,
    `resolved_url` = NULL,
    initialize = function(
        `pid`=NULL, `pid_scheme`=NULL, `resolvable_status`=FALSE, `resolved_url`=NULL, ...
    ) {
      local.optional.var <- list(...)
      if (!is.null(`pid`)) {
        stopifnot(is.character(`pid`), length(`pid`) == 1)
        self$`pid` <- `pid`
      }
      if (!is.null(`pid_scheme`)) {
        stopifnot(is.character(`pid_scheme`), length(`pid_scheme`) == 1)
        self$`pid_scheme` <- `pid_scheme`
      }
      if (!is.null(`resolvable_status`)) {
        stopifnot(is.logical(`resolvable_status`), length(`resolvable_status`) == 1)
        self$`resolvable_status` <- `resolvable_status`
      }
      if (!is.null(`resolved_url`)) {
        stopifnot(is.character(`resolved_url`), length(`resolved_url`) == 1)
        self$`resolved_url` <- `resolved_url`
      }
    },
    toJSON = function() {
      PersistenceOutputObject <- list()
      if (!is.null(self$`pid`)) {
        PersistenceOutputObject[['pid']] <-
          self$`pid`
      }
      if (!is.null(self$`pid_scheme`)) {
        PersistenceOutputObject[['pid_scheme']] <-
          self$`pid_scheme`
      }
      if (!is.null(self$`resolvable_status`)) {
        PersistenceOutputObject[['resolvable_status']] <-
          self$`resolvable_status`
      }
      if (!is.null(self$`resolved_url`)) {
        PersistenceOutputObject[['resolved_url']] <-
          self$`resolved_url`
      }

      PersistenceOutputObject
    },
    fromJSON = function(PersistenceOutputJson) {
      PersistenceOutputObject <- jsonlite::fromJSON(PersistenceOutputJson)
      if (!is.null(PersistenceOutputObject$`pid`)) {
        self$`pid` <- PersistenceOutputObject$`pid`
      }
      if (!is.null(PersistenceOutputObject$`pid_scheme`)) {
        self$`pid_scheme` <- PersistenceOutputObject$`pid_scheme`
      }
      if (!is.null(PersistenceOutputObject$`resolvable_status`)) {
        self$`resolvable_status` <- PersistenceOutputObject$`resolvable_status`
      }
      if (!is.null(PersistenceOutputObject$`resolved_url`)) {
        self$`resolved_url` <- PersistenceOutputObject$`resolved_url`
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`pid`)) {
        sprintf(
        '"pid":
          "%s"
                ',
        self$`pid`
        )},
        if (!is.null(self$`pid_scheme`)) {
        sprintf(
        '"pid_scheme":
          "%s"
                ',
        self$`pid_scheme`
        )},
        if (!is.null(self$`resolvable_status`)) {
        sprintf(
        '"resolvable_status":
          %s
                ',
        tolower(self$`resolvable_status`)
        )},
        if (!is.null(self$`resolved_url`)) {
        sprintf(
        '"resolved_url":
          "%s"
                ',
        self$`resolved_url`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(PersistenceOutputJson) {
      PersistenceOutputObject <- jsonlite::fromJSON(PersistenceOutputJson)
      self$`pid` <- PersistenceOutputObject$`pid`
      self$`pid_scheme` <- PersistenceOutputObject$`pid_scheme`
      self$`resolvable_status` <- PersistenceOutputObject$`resolvable_status`
      self$`resolved_url` <- PersistenceOutputObject$`resolved_url`
      self
    }
  )
)
