# F-UJI
#
# A Service for Evaluating Research Data Objects Based on <a href ='https://doi.org/10.5281/zenodo.3775793'>FAIRsFAIR Metrics</a>. <p> This work was supported by the <a href='https://www.fairsfair.eu/'>FAIRsFAIR</a> project (H2020-INFRAEOSC-2018-2020 Grant Agreement 831558).
#
# The version of the OpenAPI document: 1.1.0
# Contact: anusuriya.devaraju@googlemail.com
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title RelatedResourceOutputInner
#'
#' @description RelatedResourceOutputInner Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field related_resource  character [optional]
#'
#' @field relation_type  character [optional]
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
RelatedResourceOutputInner <- R6::R6Class(
  'RelatedResourceOutputInner',
  public = list(
    `related_resource` = NULL,
    `relation_type` = NULL,
    initialize = function(
        `related_resource`=NULL, `relation_type`=NULL, ...
    ) {
      local.optional.var <- list(...)
      if (!is.null(`related_resource`)) {
        stopifnot(is.character(`related_resource`), length(`related_resource`) == 1)
        self$`related_resource` <- `related_resource`
      }
      if (!is.null(`relation_type`)) {
        stopifnot(is.character(`relation_type`), length(`relation_type`) == 1)
        self$`relation_type` <- `relation_type`
      }
    },
    toJSON = function() {
      RelatedResourceOutputInnerObject <- list()
      if (!is.null(self$`related_resource`)) {
        RelatedResourceOutputInnerObject[['related_resource']] <-
          self$`related_resource`
      }
      if (!is.null(self$`relation_type`)) {
        RelatedResourceOutputInnerObject[['relation_type']] <-
          self$`relation_type`
      }

      RelatedResourceOutputInnerObject
    },
    fromJSON = function(RelatedResourceOutputInnerJson) {
      RelatedResourceOutputInnerObject <- jsonlite::fromJSON(RelatedResourceOutputInnerJson)
      if (!is.null(RelatedResourceOutputInnerObject$`related_resource`)) {
        self$`related_resource` <- RelatedResourceOutputInnerObject$`related_resource`
      }
      if (!is.null(RelatedResourceOutputInnerObject$`relation_type`)) {
        self$`relation_type` <- RelatedResourceOutputInnerObject$`relation_type`
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`related_resource`)) {
        sprintf(
        '"related_resource":
          "%s"
                ',
        self$`related_resource`
        )},
        if (!is.null(self$`relation_type`)) {
        sprintf(
        '"relation_type":
          "%s"
                ',
        self$`relation_type`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(RelatedResourceOutputInnerJson) {
      RelatedResourceOutputInnerObject <- jsonlite::fromJSON(RelatedResourceOutputInnerJson)
      self$`related_resource` <- RelatedResourceOutputInnerObject$`related_resource`
      self$`relation_type` <- RelatedResourceOutputInnerObject$`relation_type`
      self
    }
  )
)
