# F-UJI
#
# A Service for Evaluating Research Data Objects Based on <a href ='https://doi.org/10.5281/zenodo.3775793'>FAIRsFAIR Metrics</a>. <p> This work was supported by the <a href='https://www.fairsfair.eu/'>FAIRsFAIR</a> project (H2020-INFRAEOSC-2018-2020 Grant Agreement 831558).
#
# The version of the OpenAPI document: 1.1.0
# Contact: anusuriya.devaraju@googlemail.com
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title SearchableAllOf
#'
#' @description SearchableAllOf Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field output  \link{SearchableOutput} [optional]
#'
#' @field test_debug  list( character ) [optional]
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
SearchableAllOf <- R6::R6Class(
  'SearchableAllOf',
  public = list(
    `output` = NULL,
    `test_debug` = NULL,
    initialize = function(
        `output`=NULL, `test_debug`=NULL, ...
    ) {
      local.optional.var <- list(...)
      if (!is.null(`output`)) {
        stopifnot(R6::is.R6(`output`))
        self$`output` <- `output`
      }
      if (!is.null(`test_debug`)) {
        stopifnot(is.vector(`test_debug`), length(`test_debug`) != 0)
        sapply(`test_debug`, function(x) stopifnot(is.character(x)))
        self$`test_debug` <- `test_debug`
      }
    },
    toJSON = function() {
      SearchableAllOfObject <- list()
      if (!is.null(self$`output`)) {
        SearchableAllOfObject[['output']] <-
          self$`output`$toJSON()
      }
      if (!is.null(self$`test_debug`)) {
        SearchableAllOfObject[['test_debug']] <-
          self$`test_debug`
      }

      SearchableAllOfObject
    },
    fromJSON = function(SearchableAllOfJson) {
      SearchableAllOfObject <- jsonlite::fromJSON(SearchableAllOfJson)
      if (!is.null(SearchableAllOfObject$`output`)) {
        outputObject <- SearchableOutput$new()
        outputObject$fromJSON(jsonlite::toJSON(SearchableAllOfObject$output, auto_unbox = TRUE, digits = NA))
        self$`output` <- outputObject
      }
      if (!is.null(SearchableAllOfObject$`test_debug`)) {
        self$`test_debug` <- ApiClient$new()$deserializeObj(SearchableAllOfObject$`test_debug`, "array[character]", loadNamespace("rfuji"))
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`output`)) {
        sprintf(
        '"output":
        %s
        ',
        jsonlite::toJSON(self$`output`$toJSON(), auto_unbox=TRUE, digits = NA)
        )},
        if (!is.null(self$`test_debug`)) {
        sprintf(
        '"test_debug":
           [%s]
        ',
        paste(unlist(lapply(self$`test_debug`, function(x) paste0('"', x, '"'))), collapse=",")
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(SearchableAllOfJson) {
      SearchableAllOfObject <- jsonlite::fromJSON(SearchableAllOfJson)
      self$`output` <- SearchableOutput$new()$fromJSON(jsonlite::toJSON(SearchableAllOfObject$output, auto_unbox = TRUE, digits = NA))
      self$`test_debug` <- ApiClient$new()$deserializeObj(SearchableAllOfObject$`test_debug`, "array[character]", loadNamespace("rfuji"))
      self
    }
  )
)
