# F-UJI
#
# A Service for Evaluating Research Data Objects Based on <a href ='https://doi.org/10.5281/zenodo.3775793'>FAIRsFAIR Metrics</a>. <p> This work was supported by the <a href='https://www.fairsfair.eu/'>FAIRsFAIR</a> project (H2020-INFRAEOSC-2018-2020 Grant Agreement 831558).
#
# The version of the OpenAPI document: 1.1.0
# Contact: anusuriya.devaraju@googlemail.com
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title SearchableOutput
#'
#' @description SearchableOutput Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field search_mechanisms  list( \link{OutputSearchMechanisms} ) [optional]
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
SearchableOutput <- R6::R6Class(
  'SearchableOutput',
  public = list(
    `search_mechanisms` = NULL,
    initialize = function(
        `search_mechanisms`=NULL, ...
    ) {
      local.optional.var <- list(...)
      if (!is.null(`search_mechanisms`)) {
        stopifnot(is.vector(`search_mechanisms`), length(`search_mechanisms`) != 0)
        sapply(`search_mechanisms`, function(x) stopifnot(R6::is.R6(x)))
        self$`search_mechanisms` <- `search_mechanisms`
      }
    },
    toJSON = function() {
      SearchableOutputObject <- list()
      if (!is.null(self$`search_mechanisms`)) {
        SearchableOutputObject[['search_mechanisms']] <-
          lapply(self$`search_mechanisms`, function(x) x$toJSON())
      }

      SearchableOutputObject
    },
    fromJSON = function(SearchableOutputJson) {
      SearchableOutputObject <- jsonlite::fromJSON(SearchableOutputJson)
      if (!is.null(SearchableOutputObject$`search_mechanisms`)) {
        self$`search_mechanisms` <- ApiClient$new()$deserializeObj(SearchableOutputObject$`search_mechanisms`, "array[OutputSearchMechanisms]", loadNamespace("rfuji"))
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`search_mechanisms`)) {
        sprintf(
        '"search_mechanisms":
        [%s]
',
        paste(sapply(self$`search_mechanisms`, function(x) jsonlite::toJSON(x$toJSON(), auto_unbox=TRUE, digits = NA)), collapse=",")
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(SearchableOutputJson) {
      SearchableOutputObject <- jsonlite::fromJSON(SearchableOutputJson)
      self$`search_mechanisms` <- ApiClient$new()$deserializeObj(SearchableOutputObject$`search_mechanisms`, "array[OutputSearchMechanisms]", loadNamespace("rfuji"))
      self
    }
  )
)
