# F-UJI
#
# A Service for Evaluating Research Data Objects Based on <a href ='https://doi.org/10.5281/zenodo.3775793'>FAIRsFAIR Metrics</a>. <p> This work was supported by the <a href='https://www.fairsfair.eu/'>FAIRsFAIR</a> project (H2020-INFRAEOSC-2018-2020 Grant Agreement 831558).
#
# The version of the OpenAPI document: 1.1.0
# Contact: anusuriya.devaraju@googlemail.com
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title SemanticVocabularyOutputInner
#'
#' @description SemanticVocabularyOutputInner Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field namespace  character [optional]
#'
#' @field is_namespace_active  character [optional]
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
SemanticVocabularyOutputInner <- R6::R6Class(
  'SemanticVocabularyOutputInner',
  public = list(
    `namespace` = NULL,
    `is_namespace_active` = NULL,
    initialize = function(
        `namespace`=NULL, `is_namespace_active`=FALSE, ...
    ) {
      local.optional.var <- list(...)
      if (!is.null(`namespace`)) {
        stopifnot(is.character(`namespace`), length(`namespace`) == 1)
        self$`namespace` <- `namespace`
      }
      if (!is.null(`is_namespace_active`)) {
        stopifnot(is.logical(`is_namespace_active`), length(`is_namespace_active`) == 1)
        self$`is_namespace_active` <- `is_namespace_active`
      }
    },
    toJSON = function() {
      SemanticVocabularyOutputInnerObject <- list()
      if (!is.null(self$`namespace`)) {
        SemanticVocabularyOutputInnerObject[['namespace']] <-
          self$`namespace`
      }
      if (!is.null(self$`is_namespace_active`)) {
        SemanticVocabularyOutputInnerObject[['is_namespace_active']] <-
          self$`is_namespace_active`
      }

      SemanticVocabularyOutputInnerObject
    },
    fromJSON = function(SemanticVocabularyOutputInnerJson) {
      SemanticVocabularyOutputInnerObject <- jsonlite::fromJSON(SemanticVocabularyOutputInnerJson)
      if (!is.null(SemanticVocabularyOutputInnerObject$`namespace`)) {
        self$`namespace` <- SemanticVocabularyOutputInnerObject$`namespace`
      }
      if (!is.null(SemanticVocabularyOutputInnerObject$`is_namespace_active`)) {
        self$`is_namespace_active` <- SemanticVocabularyOutputInnerObject$`is_namespace_active`
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`namespace`)) {
        sprintf(
        '"namespace":
          "%s"
                ',
        self$`namespace`
        )},
        if (!is.null(self$`is_namespace_active`)) {
        sprintf(
        '"is_namespace_active":
          %s
                ',
        tolower(self$`is_namespace_active`)
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(SemanticVocabularyOutputInnerJson) {
      SemanticVocabularyOutputInnerObject <- jsonlite::fromJSON(SemanticVocabularyOutputInnerJson)
      self$`namespace` <- SemanticVocabularyOutputInnerObject$`namespace`
      self$`is_namespace_active` <- SemanticVocabularyOutputInnerObject$`is_namespace_active`
      self
    }
  )
)
