# F-UJI
#
# A Service for Evaluating Research Data Objects Based on <a href ='https://doi.org/10.5281/zenodo.3775793'>FAIRsFAIR Metrics</a>. <p> This work was supported by the <a href='https://www.fairsfair.eu/'>FAIRsFAIR</a> project (H2020-INFRAEOSC-2018-2020 Grant Agreement 831558).
#
# The version of the OpenAPI document: 1.1.0
# Contact: anusuriya.devaraju@googlemail.com
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title StandardisedProtocolDataOutput
#'
#' @description StandardisedProtocolDataOutput Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field standard_data_protocol  character [optional]
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
StandardisedProtocolDataOutput <- R6::R6Class(
  'StandardisedProtocolDataOutput',
  public = list(
    `standard_data_protocol` = NULL,
    initialize = function(
        `standard_data_protocol`=NULL, ...
    ) {
      local.optional.var <- list(...)
      if (!is.null(`standard_data_protocol`)) {
        stopifnot(is.character(`standard_data_protocol`), length(`standard_data_protocol`) == 1)
        self$`standard_data_protocol` <- `standard_data_protocol`
      }
    },
    toJSON = function() {
      StandardisedProtocolDataOutputObject <- list()
      if (!is.null(self$`standard_data_protocol`)) {
        StandardisedProtocolDataOutputObject[['standard_data_protocol']] <-
          self$`standard_data_protocol`
      }

      StandardisedProtocolDataOutputObject
    },
    fromJSON = function(StandardisedProtocolDataOutputJson) {
      StandardisedProtocolDataOutputObject <- jsonlite::fromJSON(StandardisedProtocolDataOutputJson)
      if (!is.null(StandardisedProtocolDataOutputObject$`standard_data_protocol`)) {
        self$`standard_data_protocol` <- StandardisedProtocolDataOutputObject$`standard_data_protocol`
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`standard_data_protocol`)) {
        sprintf(
        '"standard_data_protocol":
          "%s"
                ',
        self$`standard_data_protocol`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(StandardisedProtocolDataOutputJson) {
      StandardisedProtocolDataOutputObject <- jsonlite::fromJSON(StandardisedProtocolDataOutputJson)
      self$`standard_data_protocol` <- StandardisedProtocolDataOutputObject$`standard_data_protocol`
      self
    }
  )
)
