# F-UJI
#
# A Service for Evaluating Research Data Objects Based on <a href ='https://doi.org/10.5281/zenodo.3775793'>FAIRsFAIR Metrics</a>. <p> This work was supported by the <a href='https://www.fairsfair.eu/'>FAIRsFAIR</a> project (H2020-INFRAEOSC-2018-2020 Grant Agreement 831558).
#
# The version of the OpenAPI document: 1.1.0
# Contact: anusuriya.devaraju@googlemail.com
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title StandardisedProtocolMetadataOutput
#'
#' @description StandardisedProtocolMetadataOutput Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field standard_metadata_protocol  character [optional]
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
StandardisedProtocolMetadataOutput <- R6::R6Class(
  'StandardisedProtocolMetadataOutput',
  public = list(
    `standard_metadata_protocol` = NULL,
    initialize = function(
        `standard_metadata_protocol`=NULL, ...
    ) {
      local.optional.var <- list(...)
      if (!is.null(`standard_metadata_protocol`)) {
        stopifnot(is.character(`standard_metadata_protocol`), length(`standard_metadata_protocol`) == 1)
        self$`standard_metadata_protocol` <- `standard_metadata_protocol`
      }
    },
    toJSON = function() {
      StandardisedProtocolMetadataOutputObject <- list()
      if (!is.null(self$`standard_metadata_protocol`)) {
        StandardisedProtocolMetadataOutputObject[['standard_metadata_protocol']] <-
          self$`standard_metadata_protocol`
      }

      StandardisedProtocolMetadataOutputObject
    },
    fromJSON = function(StandardisedProtocolMetadataOutputJson) {
      StandardisedProtocolMetadataOutputObject <- jsonlite::fromJSON(StandardisedProtocolMetadataOutputJson)
      if (!is.null(StandardisedProtocolMetadataOutputObject$`standard_metadata_protocol`)) {
        self$`standard_metadata_protocol` <- StandardisedProtocolMetadataOutputObject$`standard_metadata_protocol`
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`standard_metadata_protocol`)) {
        sprintf(
        '"standard_metadata_protocol":
          "%s"
                ',
        self$`standard_metadata_protocol`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(StandardisedProtocolMetadataOutputJson) {
      StandardisedProtocolMetadataOutputObject <- jsonlite::fromJSON(StandardisedProtocolMetadataOutputJson)
      self$`standard_metadata_protocol` <- StandardisedProtocolMetadataOutputObject$`standard_metadata_protocol`
      self
    }
  )
)
