# F-UJI
#
# A Service for Evaluating Research Data Objects Based on <a href ='https://doi.org/10.5281/zenodo.3775793'>FAIRsFAIR Metrics</a>. <p> This work was supported by the <a href='https://www.fairsfair.eu/'>FAIRsFAIR</a> project (H2020-INFRAEOSC-2018-2020 Grant Agreement 831558).
#
# The version of the OpenAPI document: 1.1.0
# Contact: anusuriya.devaraju@googlemail.com
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title UniquenessOutput
#'
#' @description UniquenessOutput Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field guid  character [optional]
#'
#' @field guid_scheme  character [optional]
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
UniquenessOutput <- R6::R6Class(
  'UniquenessOutput',
  public = list(
    `guid` = NULL,
    `guid_scheme` = NULL,
    initialize = function(
        `guid`=NULL, `guid_scheme`=NULL, ...
    ) {
      local.optional.var <- list(...)
      if (!is.null(`guid`)) {
        stopifnot(is.character(`guid`), length(`guid`) == 1)
        self$`guid` <- `guid`
      }
      if (!is.null(`guid_scheme`)) {
        stopifnot(is.character(`guid_scheme`), length(`guid_scheme`) == 1)
        self$`guid_scheme` <- `guid_scheme`
      }
    },
    toJSON = function() {
      UniquenessOutputObject <- list()
      if (!is.null(self$`guid`)) {
        UniquenessOutputObject[['guid']] <-
          self$`guid`
      }
      if (!is.null(self$`guid_scheme`)) {
        UniquenessOutputObject[['guid_scheme']] <-
          self$`guid_scheme`
      }

      UniquenessOutputObject
    },
    fromJSON = function(UniquenessOutputJson) {
      UniquenessOutputObject <- jsonlite::fromJSON(UniquenessOutputJson)
      if (!is.null(UniquenessOutputObject$`guid`)) {
        self$`guid` <- UniquenessOutputObject$`guid`
      }
      if (!is.null(UniquenessOutputObject$`guid_scheme`)) {
        self$`guid_scheme` <- UniquenessOutputObject$`guid_scheme`
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`guid`)) {
        sprintf(
        '"guid":
          "%s"
                ',
        self$`guid`
        )},
        if (!is.null(self$`guid_scheme`)) {
        sprintf(
        '"guid_scheme":
          "%s"
                ',
        self$`guid_scheme`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(UniquenessOutputJson) {
      UniquenessOutputObject <- jsonlite::fromJSON(UniquenessOutputJson)
      self$`guid` <- UniquenessOutputObject$`guid`
      self$`guid_scheme` <- UniquenessOutputObject$`guid_scheme`
      self
    }
  )
)
